SUBDIRS=	drv_i

EXPORTSFILES=	liuclient.h tantalclient.h
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
