#ifndef __KARPOV_MONSTER_DRV_I_H
#define __KARPOV_MONSTER_DRV_I_H


// r7,w1,r7,w1,r7,w1,r7,w1,r7,w1,r7,w1,r7,w1,r7,w1,r7,w1,r7,w1
enum
{
    KARPOV_MONSTER_CHANOFS_UX1    = 0,
    KARPOV_MONSTER_CHANOFS_UX2    = 1,
    KARPOV_MONSTER_CHANOFS_UY1    = 2,
    KARPOV_MONSTER_CHANOFS_UY2    = 3,
    KARPOV_MONSTER_CHANOFS_X      = 4,
    KARPOV_MONSTER_CHANOFS_Y      = 5,
    KARPOV_MONSTER_CHANOFS_UNUSED = 6,
    KARPOV_MONSTER_CHANOFS_AMPL   = 7,
    
    KARPOV_MONSTER_CHANS_PER_UNIT = 8,  // # of channels per ADC+filter pack

    KARPOV_MONSTER_MAXUNITS       = 10, // Max # of ADC+filter units per crate
    KARPOV_MONSTER_NUMCHANS       =
        KARPOV_MONSTER_CHANS_PER_UNIT * KARPOV_MONSTER_MAXUNITS
};


#endif /* __KARPOV_MONSTER_DRV_I_H */
