DRV_INTERFACES= \
		nadc333_drv_i.h nadc200_drv_i.h nadc502_drv_i.h nadc4_drv_i.h \
		s2v_drv_i.h \
		v0628_drv_i.h g0601_drv_i.h gzi11_drv_i.h \
		\
		cankoz_common_drv_i.h kozdev_common_drv_i.h \
		canadc40_drv_i.h candac16_drv_i.h \
		cac208_drv_i.h cdac20_drv_i.h ceac124_drv_i.h \
		cpks8_drv_i.h cgvi8_drv_i.h curvv_drv_i.h cir8_drv_i.h \
		caniva_drv_i.h  \
		cgti_drv_i.h \
                canpcsc8_drv_i.h \
		k5045bbs_drv_i.h \
		vsdc2_drv_i.h \
                panov_ubs_drv_i.h tvac320_drv_i.h vv2222_drv_i.h \
		yamctr_drv_i.h \
		senkov_vip_drv_i.h senkov_ebc_drv_i.h weld02_drv_i.h \
		xcac208_drv_i.h xceac124_drv_i.h xcdac20_drv_i.h xcead20_drv_i.h \
		\
		v06xx_drv_i.h u0632_drv_i.h \
		frolov_d16_drv_i.h frolov_spd_drv_i.h nfrolov_d16_drv_i.h \
		frolov_bl700_drv_i.h \
		karpov_monster_drv_i.h \
		g0401_drv_i.h l0403_drv_i.h \
		c0601_drv_i.h c0609_drv_i.h c0612_drv_i.h b0641_drv_i.h \
		\
                v0308_drv_i.h \
		\
		dds300_drv_i.h dds500_drv_i.h \
		frolov_bfp_drv_i.h frolov_bfp2_drv_i.h frolov_bfp16_drv_i.h \
		\
		sukh_comm_drv_i.h \
		\
		\
		vadc16_drv_i.h vdac20_drv_i.h \
		\
		adc200me_drv_i.h adc812me_drv_i.h \
		dl200me_drv_i.h \
		pisoenc600_drv_i.h \
		\
		kshd485_drv_i.h nkshd485_drv_i.h \
		\
		ottcamv_drv_i.h tsycamv_drv_i.h \
		ottcam_drv_i.h \
		tsycamz_drv_i.h
GIVEN_FILES=	$(DRV_INTERFACES)

EXPORTSFILES=	$(DRV_INTERFACES)
EXPORTSDIR=	include/drv_i

######################################################################
PRJDIR=		../..
include		$(PRJDIR)/PrjRules.mk
######################################################################
