#ifndef __XCANDAC16_DRV_I_H
#define __XCANDAC16_DRV_I_H


#include "drv_i/kozdev_common_drv_i.h"


// w40,r20,w8,r8,w1,r1,r22,r100,w64,r36
enum
{
    XCANDAC16_CONFIG_CHAN_base     = KOZDEV_CONFIG_CHAN_base,
      XCANDAC16_CONFIG_CHAN_count  = KOZDEV_CONFIG_CHAN_count,

    /*  */
    XCANDAC16_MODE_CHAN_base       = KOZDEV_MODE_CHAN_base,
      XCANDAC16_MODE_CHAN_count    = KOZDEV_MODE_CHAN_count,

    XCANDAC16_CHAN_DO_RESET        = KOZDEV_CHAN_DO_RESET,
    zXCANDAC16_CHAN_ADC_MODE        = KOZDEV_CHAN_ADC_MODE,
    XCANDAC16_CHAN_ADC_BEG         = KOZDEV_CHAN_ADC_BEG,
    XCANDAC16_CHAN_ADC_END         = KOZDEV_CHAN_ADC_END,
    XCANDAC16_CHAN_ADC_TIMECODE    = KOZDEV_CHAN_ADC_TIMECODE,
    XCANDAC16_CHAN_ADC_GAIN        = KOZDEV_CHAN_ADC_GAIN,
    XCANDAC16_CHAN_RESERVED6       = KOZDEV_CHAN_RESERVED6,
    XCANDAC16_CHAN_RESERVED7       = KOZDEV_CHAN_RESERVED7,
    XCANDAC16_CHAN_RESERVED8       = KOZDEV_CHAN_RESERVED8,
    XCANDAC16_CHAN_OUT_MODE        = KOZDEV_CHAN_OUT_MODE,

    XCANDAC16_CHAN_DO_TAB_DROP     = KOZDEV_CHAN_DO_TAB_DROP,
    XCANDAC16_CHAN_DO_TAB_ACTIVATE = KOZDEV_CHAN_DO_TAB_ACTIVATE,
    XCANDAC16_CHAN_DO_TAB_START    = KOZDEV_CHAN_DO_TAB_START,
    XCANDAC16_CHAN_DO_TAB_STOP     = KOZDEV_CHAN_DO_TAB_STOP,
    XCANDAC16_CHAN_DO_TAB_PAUSE    = KOZDEV_CHAN_DO_TAB_PAUSE,
    XCANDAC16_CHAN_DO_TAB_RESUME   = KOZDEV_CHAN_DO_TAB_RESUME,
      XCANDAC16_CHAN_DO_TAB_base = KOZDEV_CHAN_DO_TAB_base,
      XCANDAC16_CHAN_DO_TAB_cnt  = KOZDEV_CHAN_DO_TAB_cnt,
    XCANDAC16_CHAN_RESERVED16      = KOZDEV_CHAN_RESERVED16,
    XCANDAC16_CHAN_RESERVED17      = KOZDEV_CHAN_RESERVED17,
    XCANDAC16_CHAN_RESERVED18      = KOZDEV_CHAN_RESERVED18,
    XCANDAC16_CHAN_RESERVED19      = KOZDEV_CHAN_RESERVED19,

    /*  */
    XCANDAC16_CHAN_STD_WR_base     = KOZDEV_CHAN_STD_WR_base,
      XCANDAC16_CHAN_STD_WR_count  = KOZDEV_CHAN_STD_WR_count,
    zXCANDAC16_CHAN_DO_CALB_DAC     = KOZDEV_CHAN_DO_CALB_DAC,
    zXCANDAC16_CHAN_AUTOCALB_ONOFF  = KOZDEV_CHAN_AUTOCALB_ONOFF,
    zXCANDAC16_CHAN_AUTOCALB_SECS   = KOZDEV_CHAN_AUTOCALB_SECS,
    zXCANDAC16_CHAN_DIGCORR_MODE    = KOZDEV_CHAN_DIGCORR_MODE,

    /*  */
    XCANDAC16_CHAN_STD_RD_base     = KOZDEV_CHAN_STD_RD_base,
      XCANDAC16_CHAN_STD_RD_count  = KOZDEV_CHAN_STD_RD_count,
    XCANDAC16_CHAN_HW_VER          = KOZDEV_CHAN_HW_VER,
    XCANDAC16_CHAN_SW_VER          = KOZDEV_CHAN_SW_VER,
    zXCANDAC16_CHAN_DIGCORR_FACTOR  = KOZDEV_CHAN_DIGCORR_FACTOR,

    /*** I/O registers **********************************************/
    XCANDAC16_CHAN_REGS_base       = KOZDEV_CHAN_REGS_base,
    XCANDAC16_CHAN_REGS_WR8_base   = KOZDEV_CHAN_REGS_WR8_base,
    XCANDAC16_CHAN_REGS_RD8_base   = KOZDEV_CHAN_REGS_RD8_base,
    XCANDAC16_CHAN_REGS_WR1        = KOZDEV_CHAN_REGS_WR1,
    XCANDAC16_CHAN_REGS_RD1        = KOZDEV_CHAN_REGS_RD1,
    XCANDAC16_CHAN_REGS_last       = KOZDEV_CHAN_REGS_last,

    XCANDAC16_CHAN_REGS_RSVD_B     = KOZDEV_CHAN_REGS_RSVD_B,
    XCANDAC16_CHAN_REGS_RSVD_E     = KOZDEV_CHAN_REGS_RSVD_E,

    /* Regular ADC/DAC channels *************************************/
    zXCANDAC16_CHAN_ADC_n_base      = KOZDEV_CHAN_ADC_n_base,
      zXCANDAC16_CHAN_ADC_n_count   = 0,
      zXCANDAC16_CHAN_ADC_n_maxcnt  = KOZDEV_CHAN_ADC_n_maxcnt,

    XCANDAC16_CHAN_OUT_n_base      = KOZDEV_CHAN_OUT_n_base,
      XCANDAC16_CHAN_OUT_n_count   = 16,
      XCANDAC16_CHAN_OUT_n_maxcnt  = KOZDEV_CHAN_OUT_n_maxcnt,
    XCANDAC16_CHAN_OUT_RATE_n_base = KOZDEV_CHAN_OUT_RATE_n_base,
    XCANDAC16_CHAN_OUT_CUR_n_base  = KOZDEV_CHAN_OUT_CUR_n_base,
      XCANDAC16_CHAN_OUT_RESERVED_count = KOZDEV_CHAN_OUT_RESERVED_count,

    XCANDAC16_NUMCHANS = KOZDEV_NUMCHANS
};

enum
{
    XCANDAC16_OUT_MODE_NORM   = 0,
    XCANDAC16_OUT_MODE_TABLE  = 1,
};

enum
{
    XCANDAC16_VAL_DISABLE_TABLE_CHAN = 20*1000*1000,  // 20V or higher -- disable channel

};


#endif /* __XCANDAC16_DRV_I_H */
