MONO_C_FILES=	tsycam_drv.so \
		ottcamv_drv.so tsycamv_drv.so \
		ottcam_drv.so

######################################################################
PRJDIR=		../..
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################

ottcam_drv.so:	$(LIBPZFRAME_DRV)
