EXPORTSFILES=	cx-starter-linac.conf cx-starter-tino.conf \
		blklist-linac-51.lst blklist-linac-52.lst
EXPORTSDIR=	configs

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
