######################################################################
#                                                                    #
#  programs/Makefile                                                 #
#      Rules for making CX programs/ subtree                         #
#                                                                    #
######################################################################

SUBDIRS=	
DRIVERS=	noop_drv.so remdrv_drv.so
MONO_C_FILES=	$(DRIVERS)

TOPDIR=		../..
include $(TOPDIR)/TopRules.mk

DIR_CFLAGS=	-fPIC

# #### END OF Makefile ###############################################
