######################################################################
#                                                                    #
#  lib/MotifKnobs/Makefile                                           #
#      Rules for making Motif Knobs library                          #
#                                                                    #
######################################################################

ARLIBS=		libMotifKnobs.a
libMotifKnobs.a_COMPONENTS=	MotifKnobs_internals.o \
				MotifKnobs_knobset.o \
				MotifKnobs_text_knob.o \
				MotifKnobs_selector_knob.o \
				MotifKnobs_choicebs_knob.o \
				MotifKnobs_alarmonoffled_knob.o \
				MotifKnobs_button_knob.o \
				MotifKnobs_label_noop.o \
				MotifKnobs_separator_noop.o \
				MotifKnobs_grid_cont.o \
				MotifKnobs_subwin_cont.o \
				MotifKnobs_canvas_cont.o \
				MotifKnobs_lrtb_grpg.o

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
