SUBDIRS=	pixmaps

EXPORTSFILES=	ndbp_elemlist.h
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
