SUBDIRS=	

EXPORTSFILES=	weldclient.h
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
