######################################################################
#                                                                    #
#  lib/Cdr/Makefile                                                  #
#      Rules for making Cx Data Representation library               #
#                                                                    #
######################################################################

ARLIBS=		libCdr.a
libCdr.a_COMPONENTS=	Cdr_treeproc.o Cdr_err.o Cdr_plugmgr.o \
			Cdr_file_ldr.o Cdr_file_via_ppf4td.o Cdr_via_ppf4td.o

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
