MONO_C_FILES=	fadiffer_drv.so doorilks_drv.so

######################################################################
PRJDIR=		..
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################
