EXPORTSFILES=	$(EXES) $(MONO_C_FILES)
EXPORTSDIR=	bin

include		$(TOPDIR)/TopRules.mk

DIR_LIBS=	$(MOTIF_LIBS)
ifneq "$(strip $(EXES) $(MONO_C_FILES))" ""
  $(EXES) $(MONO_C_FILES):$(LOCAL_LIBDEPS) \
			$(LIBCHL) $(LIBKNOBS) \
			$(LIBXH) $(LIBAUXMOTIFWIDGETS) \
			$(LIBCDR) $(LIBDATATREE) $(LIBCDA) \
			$(LIBCX_ASYNC) $(LIBUSEFUL) $(LIBXH_CXSCHEDULER) \
			$(LIBMISC)
endif
