ARLIBS=			libcda.a
libcda.a_COMPONENTS=	cda.o cda_math.o cda_err.o

EXPORTSFILES=		$(ARLIBS)
EXPORTSDIR=		lib

SPECIFIC_CFLAGS=	-fPIC

######################################################################
TOPDIR=	        ../..
include		$(TOPDIR)/TopRules.mk
######################################################################
