######################################################################
#                                                                    #
#  lib/AuxMotifWidgets/Makefile                                      #
#      Rules for making nonstandard-Motif-widgets library            #
#                                                                    #
######################################################################

ARLIBS=		libAuxMotifWidgets.a
libAuxMotifWidgets.a_COMPONENTS=	IncDecB.o \
					InputOnly.o \
					XmLiteClue.o \
					XmSepGridLayout.o

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
