EXES=		weldclient

weldclient_COMPONENTS=	weldclient.o weldclient_process_knobplugin.o


# --------------------------------------------------------------------
PRJDIR=		..
SUBDIRS=
SECTION=	programs/xmclients/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
# --------------------------------------------------------------------

weldclient:	SPECIFIC_LIBS=$(LIBDL)
