DRV_INTERFACES= \
		delayunit_drv_i.h \
		\
		psctrlunit_drv_i.h \
		\
		nadc4decimator_v1_drv_i.h \
		nadc4decimator_v2_drv_i.h \


GIVEN_FILES=	$(DRV_INTERFACES)

EXPORTSFILES=	$(DRV_INTERFACES)
EXPORTSDIR=	include/drv_i

######################################################################
PRJDIR=		../..
include		$(PRJDIR)/PrjRules.mk
######################################################################
