#ifndef __PSCTRLUNIT_DRV_I_H
#define __PSCTRLUNIT_DRV_I_H

enum
{
    PSCTRLUNIT_CHAN_GAIN0 = 0,
    PSCTRLUNIT_CHAN_GAIN1,
    PSCTRLUNIT_CHAN_GAIN2,
    PSCTRLUNIT_CHAN_GAIN3,
    PSCTRLUNIT_CHAN_GAIN4,
    PSCTRLUNIT_CHAN_GAIN5,
    PSCTRLUNIT_CHAN_GAIN6,
    PSCTRLUNIT_CHAN_GAIN7,
    PSCTRLUNIT_NUM_GAIN_CHANS = 8,

    PSCTRLUNIT_CHAN_RSRV8 = 8,
    PSCTRLUNIT_CHAN_RSRV9,

    PSCTRLUNIT_NUMCHANS,
};

enum
{
    PSCTRLUNIT_MIN_GAIN = 0,
    PSCTRLUNIT_MAX_GAIN = 15,
};

#endif /* __PSCTRLUNIT_DRV_I_H */
