DRV_INTERFACES=	ist_xcdac20_drv_i.h v1k_xcdac20_drv_i.h v3h_xa40d16_drv_i.h \
		lebedev_subharmonic_drv_i.h
GIVEN_FILES=	$(DRV_INTERFACES)

EXPORTSFILES=	$(DRV_INTERFACES)
EXPORTSDIR=	include/drv_i

######################################################################
PRJDIR=		../..
include		$(PRJDIR)/PrjRules.mk
######################################################################
