#ifndef __BPMCLIENT_H
#define __BPMCLIENT_H


#include "drv_i/karpov_monster_drv_i.h"


enum
{
    LOGD_BPM_GRAPH   = 'b' + ('p'<<8) + ('m'<<16) + ('g'<<24),
    LOGD_BPM_PROFILE = 'b' + ('p'<<8) + ('m'<<16) + ('p'<<24),
};

#define KARPOV_DELAY_BASE_C   0
#define KARPOV_MONSTER_BASE_C 15

#define KARPOV_UNIT_BASE_C(n) (KARPOV_MONSTER_BASE_C + KARPOV_MONSTER_CHANS_PER_UNIT * (n))

#define KARPOV_DELAY_C(n) (n)
#define KARPOV_UX1_C(  n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_UX1)
#define KARPOV_UX2_C(  n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_UX2)
#define KARPOV_UY1_C(  n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_UY1)
#define KARPOV_UY2_C(  n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_UY2)
#define KARPOV_X_C(    n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_X)
#define KARPOV_Y_C(    n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_Y)
#define KARPOV_AMPL_C( n) (KARPOV_UNIT_BASE_C(n) + KARPOV_MONSTER_CHANOFS_AMPL)


#endif /* __BPMCLIENT_H */
