SUBDIRS=	drv_i pixmaps

EXPORTSFILES=	
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
