MONO_C_FILES=	ist_xcdac20_drv.so v1k_xcdac20_drv.so v3h_xa40d16_drv.so

######################################################################
PRJDIR=		..
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################

ist_xcdac20_drv.so v1k_xcdac20_drv.so v3h_xa40d16_drv.so:	$(LIBVDEV)
