TOPDIR=		../..
include		$(TOPDIR)/Config.mk
# --------------------------------------------------------------------
MONO_C_FILES=	noop_drv.so sim_drv.so test_drv.so \
		remdrv_drv.so \
		trig_read_drv.so trig_write_drv.so multiplexer_drv.so \
		softwform_drv.so

######################################################################
include		DirRules.mk
######################################################################
