SUBDIRS=	include configs drivers chlclients

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
