EXPORTSFILES=	srvparams.conf \
		blklist-rack0-44.lst blklist-rack0-45.lst blklist-rack0-46.lst \
		$(foreach H, 1 2 3 4 5 6 7 8 X, blklist-rack$H-43.lst) \
		cx-starter-wolf.conf
EXPORTSDIR=	configs

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
