CSUBDIRS=	include configs drivers chlclients
XSUBDIRS=	xmclients
ifneq "$(NOX)" ""
  XSUBDIRS=     
endif
SUBDIRS=	$(CSUBDIRS) $(XSUBDIRS)

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
