PRJDIR=		../../..
V2HCAMDIR=	$(V2HDIR)/drivers/camac
SECTION=	$(V2HCAMDIR)/cm5307_ppc_drvlets/DirRules.mk
include		$(PRJDIR)/PrjRules.mk

cm5307_nadc4m_drv.d cm5307_nadc4m_drv.o:	SPECIFIC_INCLUDES=-I$(V2HCAMDIR)/src
