CSUBDIRS=	include configs chlclients drivers
XSUBDIRS=	xmclients
ifneq "$(NOX)" ""
  XSUBDIRS=     
endif
SUBDIRS=	$(CSUBDIRS) $(XSUBDIRS)

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
