CSUBDIRS=	misc useful cxlib cda Cdr pzframe vdev rem icons
XSUBDIRS=	AuxMotifWidgets Xh Knobs Chl
ifneq "$(NOX)" ""
  XSUBDIRS=	
endif
SUBDIRS=	$(CSUBDIRS) $(XSUBDIRS)

LOCAL_BCKPFILES=4PyQt/*~ Qcxscheduler/*~

######################################################################
TOPDIR=	        ..
include		$(TOPDIR)/TopRules.mk
######################################################################
