CSUBDIRS=	zzz drivers utils tests chlclients
XSUBDIRS=	runner xmclients
ifneq "$(NOX)" ""
  XSUBDIRS=	
endif
SUBDIRS=	$(CSUBDIRS) $(XSUBDIRS)

######################################################################
TOPDIR=	        ..
include		$(TOPDIR)/TopRules.mk
######################################################################
