EXPORTSFILES=	cx-starter-titan.conf blklist-titan-1.lst
EXPORTSDIR=	configs

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
