#include "common_elem_macros.h"


#define MAILBOX(id, n) \
    {id, id, NULL, "%8.4f", NULL, NULL, LOGT_WRITE1, LOGD_TEXT, LOGK_DIRECT, LOGC_NORMAL, PHYS_ID(n)}

enum
{
// RING DCCT block
DCCT_U2I = 0,
DCCT_ADC_ZERO = 1,
DCCT_MEASTIME = 2,
DCCT_BCURRENT = 3,
DCCT_STORAGE_FITLENGTH = 4,
DCCT_STORAGE_RATE = 5,
DCCT_LIFE_FITLENGTH = 6,
DCCT_LIFETIME = 7,
DCCT_MEADDLE_RUN = 8,
DCCT_CHARGE = 9,
DCCT_CHARGE_RATE =10,
DCCT_N = 11,
DCCT_N_RATE = 12,
DCCT_I2CHARGE = 13,
DCCT_I2N = 14,
DCCT_STORAGE_RATE_CALC = 15,
DCCT_LIFETIME_CALC = 16,
DCCT_MEADDLE_LOCK = 17,

// Injection Complex general automation block
IC_STATUS = 18,
IC_TASK = 19,
IC_BEAM_TO = 20,
LINAC_STATUS = 21,
RING_STATUS = 22,
IC_MIDDLE_RUNNER = 23,
IC_MIDDLE_RUN = 24,


LINAC_F_RF,
RING_F_RF,
LINAC_F_SUB,
D16_F_CLOCK,

INJEXT_MIDDLE_RUN,
INJEXT_MIDDLE_LOCK,


EKICK_START_MASK,
EKICK_START_MASK_RBV,
EKICK_START_MODE,
EKICK_START_MODE_RBV,

EKICK_GEN_C1_DLY,
EKICK_GEN_C2_DLY,
EKICK_GEN_C3_DLY,
EKICK_GEN_C4_DLY,
EKICK_FORM1P_DLY,
EKICK_FORM1N_DLY,
EKICK_FORM2P_DLY,
EKICK_FORM2N_DLY,
EKICK_GEN_C1_MASK,
EKICK_GEN_C2_MASK,
EKICK_GEN_C3_MASK,
EKICK_GEN_C4_MASK,
EKICK_FORM1P_MASK,
EKICK_FORM1N_MASK,
EKICK_FORM2P_MASK,
EKICK_FORM2N_MASK,
EKICK_U_AKK1,
EKICK_U_AKK2,

EKICK_GEN_C1_DLY_INJ,
EKICK_GEN_C2_DLY_INJ,
EKICK_GEN_C3_DLY_INJ,
EKICK_GEN_C4_DLY_INJ,
EKICK_FORM1P_DLY_INJ,
EKICK_FORM1N_DLY_INJ,
EKICK_FORM2P_DLY_INJ,
EKICK_FORM2N_DLY_INJ,
EKICK_GEN_C1_MASK_INJ,
EKICK_GEN_C2_MASK_INJ,
EKICK_GEN_C3_MASK_INJ,
EKICK_GEN_C4_MASK_INJ,
EKICK_FORM1P_MASK_INJ,
EKICK_FORM1N_MASK_INJ,
EKICK_FORM2P_MASK_INJ,
EKICK_FORM2N_MASK_INJ,
EKICK_U_AKK1_INJ,
EKICK_U_AKK2_INJ,

EKICK_GEN_C1_DLY_EXT,
EKICK_GEN_C2_DLY_EXT,
EKICK_GEN_C3_DLY_EXT,
EKICK_GEN_C4_DLY_EXT,
EKICK_FORM1P_DLY_EXT,
EKICK_FORM1N_DLY_EXT,
EKICK_FORM2P_DLY_EXT,
EKICK_FORM2N_DLY_EXT,
EKICK_GEN_C1_MASK_EXT,
EKICK_GEN_C2_MASK_EXT,
EKICK_GEN_C3_MASK_EXT,
EKICK_GEN_C4_MASK_EXT,
EKICK_FORM1P_MASK_EXT,
EKICK_FORM1N_MASK_EXT,
EKICK_FORM2P_MASK_EXT,
EKICK_FORM2N_MASK_EXT,
EKICK_U_AKK1_EXT,
EKICK_U_AKK2_EXT,

LIN_RF_FSTART,
LIN_BEAM_FSTART,
LINAC_RF_FSTART,

// action controls
IC_INJECT,
IC_EXTRACT,
IC_BEAM_STOP,
LINAC_POWERSAVE,
RING_POWERSAVE,

LIN_STARTMODE,
LIN_STARTCYCLE,
LIN_STOPSYCLE,
LIN_STARTNUM,
LIN_STARTCOUNT,
LIN_EVENTCOUNT,

//linac magnets
//General chans
LINMAG_FAIL,
LINMAG_SWC,
LINMAG_MIDDLE_RUN,
LINMAG_P,
LINMAG_Pmag,
LINMAG_Pcab,
LINMAG_Pair,
LINMAG_Pwater,

//electron linac quads
LIN_QL1_I_SET,
LIN_QL1_I_MEAS,
LIN_QL1_G_SET,
LIN_QL1_G_MEAS,
LIN_QL1_P_MAG,
LIN_QL1_P_CAB,
LIN_QL1_FAIL,


LIN_QL2_I_SET,
LIN_QL2_I_MEAS,
LIN_QL2_G_SET,
LIN_QL2_G_MEAS,
LIN_QL2_P_MAG,
LIN_QL2_P_CAB,
LIN_QL2_FAIL,

LIN_QL3_I_SET ,
LIN_QL3_I_MEAS,
LIN_QL3_G_SET,
LIN_QL3_G_MEAS,
LIN_QL3_P_MAG,
LIN_QL3_P_CAB,
LIN_QL3_FAIL,

LIN_QL4_I_SET,
LIN_QL4_I_MEAS,
LIN_QL4_G_SET,
LIN_QL4_G_MEAS,
LIN_QL4_P_MAG,
LIN_QL4_P_CAB,
LIN_QL4_FAIL,

LIN_QL5_I_SET,
LIN_QL5_I_MEAS,
LIN_QL5_G_SET,
LIN_QL5_G_MEAS,
LIN_QL5_P_MAG,
LIN_QL5_P_CAB,
LIN_QL5_FAIL,

LIN_QL6_7_I_SET,
LIN_QL6_7_I_MEAS,
LIN_QL6_7_G_SET,
LIN_QL6_7_G_MEAS,
LIN_QL6_7_P_MAG,
LIN_QL6_7_P_CAB,
LIN_QL6_7_FAIL,

LIN_QL8_9_I_SET,
LIN_QL8_9_I_MEAS,
LIN_QL8_9_G_SET,
LIN_QL8_9_G_MEAS,
LIN_QL8_9_P_MAG,
LIN_QL8_9_P_CAB,
LIN_QL8_9_FAIL,

LIN_QL10_I_SET,
LIN_QL10_I_MEAS,
LIN_QL10_G_SET,
LIN_QL10_G_MEAS,
LIN_QL10_P_MAG,
LIN_QL10_P_CAB,
LIN_QL10_FAIL,

LIN_QL11_I_SET,
LIN_QL11_I_MEAS,
LIN_QL11_G_SET,
LIN_QL11_G_MEAS,
LIN_QL11_P_MAG,
LIN_QL11_P_CAB,
LIN_QL11_FAIL,

LIN_QL12_I_SET,
LIN_QL12_I_MEAS,
LIN_QL12_G_SET,
LIN_QL12_G_MEAS,
LIN_QL12_P_MAG,
LIN_QL12_P_CAB,
LIN_QL12_FAIL,

LIN_QL13_I_SET,
LIN_QL13_I_MEAS,
LIN_QL13_G_SET,
LIN_QL13_G_MEAS,
LIN_QL13_P_MAG,
LIN_QL13_P_CAB,
LIN_QL13_FAIL,

LIN_QL14_I_SET,
LIN_QL14_I_MEAS,
LIN_QL14_G_SET,
LIN_QL14_G_MEAS,
LIN_QL14_P_MAG,
LIN_QL14_P_CAB,
LIN_QL14_FAIL,

LIN_QLB1_I_SET,
LIN_QLB1_I_MEAS,
LIN_QLB1_G_SET,
LIN_QLB1_G_MEAS,
LIN_QLB1_P_MAG,
LIN_QLB1_P_CAB,
LIN_QLB1_FAIL,

LIN_QLB2_5_I_SET,
LIN_QLB2_5_I_MEAS,
LIN_QLB2_5_G_SET,
LIN_QLB2_5_G_MEAS,
LIN_QLB2_5_P_MAG,
LIN_QLB2_5_P_CAB,
LIN_QLB2_5_FAIL,

LIN_QLB3_4_I_SET,
LIN_QLB3_4_I_MEAS,
LIN_QLB3_4_G_SET,
LIN_QLB3_4_G_MEAS,
LIN_QLB3_4_P_MAG,
LIN_QLB3_4_P_CAB,
LIN_QLB3_4_FAIL,

LIN_QLTR1_I_SET,
LIN_QLTR1_I_MEAS,
LIN_QLTR1_G_SET,
LIN_QLTR1_G_MEAS,
LIN_QLTR1_P_MAG,
LIN_QLTR1_P_CAB,
LIN_QLTR1_FAIL,

LIN_QLTR2_I_SET,
LIN_QLTR2_I_MEAS,
LIN_QLTR2_G_SET,
LIN_QLTR2_G_MEAS,
LIN_QLTR2_P_MAG,
LIN_QLTR2_P_CAB,
LIN_QLTR2_FAIL,

LIN_QLTR3_I_SET,
LIN_QLTR3_I_MEAS,
LIN_QLTR3_G_SET,
LIN_QLTR3_G_MEAS,
LIN_QLTR3_P_MAG,
LIN_QLTR3_P_CAB,
LIN_QLTR3_FAIL,

LIN_QL15_I_SET,
LIN_QL15_I_MEAS,
LIN_QL15_G_SET,
LIN_QL15_G_MEAS,
LIN_QL15_P_MAG,
LIN_QL15_P_CAB,
LIN_QL15_FAIL,

LIN_QLN_I_SET,
LIN_QLN_I_MEAS,
LIN_QLN_G_SET,
LIN_QLN_G_MEAS,
LIN_QLN_P_MAG,
LIN_QLN_P_CAB,
LIN_QLN_FAIL,

//Positron linac quads
LIN_QL16_I_SET,
LIN_QL16_I_MEAS,
LIN_QL16_G_SET,
LIN_QL16_G_MEAS,
LIN_QL16_P_MAG,
LIN_QL16_P_CAB,
LIN_QL16_FAIL,
LIN_QL16_SWC,

LIN_QL17_I_SET,
LIN_QL17_I_MEAS,
LIN_QL17_G_SET,
LIN_QL17_G_MEAS,
LIN_QL17_P_MAG,
LIN_QL17_P_CAB,
LIN_QL17_FAIL,
LIN_QL17_SWC,

LIN_QL18_I_SET,
LIN_QL18_I_MEAS,
LIN_QL18_G_SET,
LIN_QL18_G_MEAS,
LIN_QL18_P_MAG,
LIN_QL18_P_CAB,
LIN_QL18_FAIL,
LIN_QL18_SWC,

LIN_QL19_I_SET,
LIN_QL19_I_MEAS,
LIN_QL19_G_SET,
LIN_QL19_G_MEAS,
LIN_QL19_P_MAG,
LIN_QL19_P_CAB,
LIN_QL19_FAIL,
LIN_QL19_SWC,

LIN_QL20_I_SET,
LIN_QL20_I_MEAS,
LIN_QL20_G_SET,
LIN_QL20_G_MEAS,
LIN_QL20_P_MAG,
LIN_QL20_P_CAB,
LIN_QL20_FAIL,
LIN_QL20_SWC,

LIN_QL21_I_SET,
LIN_QL21_I_MEAS,
LIN_QL21_G_SET,
LIN_QL21_G_MEAS,
LIN_QL21_P_MAG,
LIN_QL21_P_CAB,
LIN_QL21_FAIL,
LIN_QL21_SWC,

LIN_QL22_I_SET,
LIN_QL22_I_MEAS,
LIN_QL22_G_SET,
LIN_QL22_G_MEAS,
LIN_QL22_P_MAG,
LIN_QL22_P_CAB,
LIN_QL22_FAIL,
LIN_QL22_SWC,

LIN_QL23_I_SET,
LIN_QL23_I_MEAS,
LIN_QL23_G_SET,
LIN_QL23_G_MEAS,
LIN_QL23_P_MAG,
LIN_QL23_P_CAB,
LIN_QL23_FAIL,
LIN_QL23_SWC,

LIN_QL24_I_SET,
LIN_QL24_I_MEAS,
LIN_QL24_G_SET,
LIN_QL24_G_MEAS,
LIN_QL24_P_MAG,
LIN_QL24_P_CAB,
LIN_QL24_FAIL,
LIN_QL24_SWC,

LIN_QL25_I_SET,
LIN_QL25_I_MEAS,
LIN_QL25_G_SET,
LIN_QL25_G_MEAS,
LIN_QL25_P_MAG,
LIN_QL25_P_CAB,
LIN_QL25_FAIL,
LIN_QL25_SWC,

LIN_QL26_I_SET,
LIN_QL26_I_MEAS,
LIN_QL26_G_SET,
LIN_QL26_G_MEAS,
LIN_QL26_P_MAG,
LIN_QL26_P_CAB,
LIN_QL26_FAIL,
LIN_QL26_SWC,

LIN_QL27_I_SET,
LIN_QL27_I_MEAS,
LIN_QL27_G_SET,
LIN_QL27_G_MEAS,
LIN_QL27_P_MAG,
LIN_QL27_P_CAB,
LIN_QL27_FAIL,
LIN_QL27_SWC,

LIN_QL28_I_SET,
LIN_QL28_I_MEAS,
LIN_QL28_G_SET,
LIN_QL28_G_MEAS,
LIN_QL28_P_MAG,
LIN_QL28_P_CAB,
LIN_QL28_FAIL,
LIN_QL28_SWC,

LIN_QL29_I_SET,
LIN_QL29_I_MEAS,
LIN_QL29_G_SET,
LIN_QL29_G_MEAS,
LIN_QL29_P_MAG,
LIN_QL29_P_CAB,
LIN_QL29_FAIL,
LIN_QL29_SWC,

LIN_QL30_I_SET,
LIN_QL30_I_MEAS,
LIN_QL30_G_SET,
LIN_QL30_G_MEAS,
LIN_QL30_P_MAG,
LIN_QL30_P_CAB,
LIN_QL30_FAIL,
LIN_QL30_SWC,

LIN_QL31_I_SET,
LIN_QL31_I_MEAS,
LIN_QL31_G_SET,
LIN_QL31_G_MEAS,
LIN_QL31_P_MAG,
LIN_QL31_P_CAB,
LIN_QL31_FAIL,
LIN_QL31_SWC,

//other linac magnets
LIN_BL1_I_SET,
LIN_BL1_I_MEAS,
LIN_BL1_P_MAG,
LIN_BL1_P_CAB,
LIN_BL1_FAIL,

LIN_BL2_I_SET,
LIN_BL2_I_MEAS,
LIN_BL2_P_MAG,
LIN_BL2_P_CAB,
LIN_BL2_FAIL,

LIN_RINGS_I_SET,
LIN_RINGS_I_MEAS,
LIN_RINGS_P_MAG,
LIN_RINGS_P_CAB,
LIN_RINGS_FAIL,

LIN_SOLE_I_SET,
LIN_SOLE_I_MEAS,
LIN_SOLE_U_MEAS,
LIN_SOLE_P_MAG,
LIN_SOLE_P_CAB,
LIN_SOLE_FAIL,
LIN_SOLE_RESET,
LIN_SOLE_SWC,

LIN_SPECTR_I_SET,
LIN_SPECTR_I_MEAS,
LIN_SPECTR_H_SET,
LIN_SPECTR_H_MEAS,
LIN_SPECTR_P_MAG,
LIN_SPECTR_P_CAB,
LIN_SPECTR_FAIL,

LIN_BEND_I_SET,
LIN_BEND_I_MEAS,
LIN_BEND_U_MEAS,
LIN_BEND_H_SET,
LIN_BEND_H_MEAS,
LIN_BEND_PC_SET,
LIN_BEND_PC_MEAS,
LIN_BEND_P_MAG,
LIN_BEND_P_CAB,
LIN_BEND_FAIL,
LIN_BEND_RESET,
LIN_BEND_SWC,

LIN_COIL1_I_SET,
LIN_COIL1_I_MEAS,
LIN_COIL1_U_MEAS,
LIN_COIL1_P_MAG,
LIN_COIL1_P_CAB,
LIN_COIL1_FAIL,
LIN_COIL1_RESET,
LIN_COIL1_SWC,

LIN_COIL2_I_SET,
LIN_COIL2_I_MEAS,
LIN_COIL2_P_MAG,
LIN_COIL2_P_CAB,
LIN_COIL2_FAIL,

LIN_SOLP_I_SET,
LIN_SOLP_I_MEAS,
LIN_SOLP_U_MEAS,
LIN_SOLP_P_MAG,
LIN_SOLP_P_CAB,
LIN_SOLP_FAIL,
LIN_SOLP_RESET,
LIN_SOLP_SWC,

LIN_SEP1_I_SET,
LIN_SEP1_I_MEAS,
LIN_SEP1_H_SET,
LIN_SEP1_H_MEAS,
LIN_SEP1_P_MAG,
LIN_SEP1_P_CAB,
LIN_SEP1_FAIL,


// ring magnets
RINGMAG_RM1_RM8_B_SET,

V2000_REQ,
V2000_FULLCHARGE,
V2000_PARTCHARGE,
V2000_SENTCHARGE,
V2000_RECDCHARGE,
V2000_ELECTRON,
V2000_POSITRON,
V2000_READY,
V2000_LOCK,
V2000_ACTTIME,
V2000_WAITTIME,
V2000_ACT,

V3_REQ,
V3_FULLCHARGE,
V3_PARTCHARGE,
V3_SENTCHARGE,
V3_RECDCHARGE,
V3_ELECTRON,
V3_POSITRON,
V3_READY,
V3_LOCK,
V3_ACTTIME,
V3_WAITTIME,
V3_ACT,

};


static groupunit_t ic_grouping[] =
{

    GLOBTABBER_START("x", 8)
        SUBELEM_START("status", "status", 7, 1)
            MAILBOX("ic",  IC_STATUS),
            MAILBOX("ic_task",  IC_TASK),
            MAILBOX("ic_beam_to",  IC_BEAM_TO),
            MAILBOX("linac",  LINAC_STATUS),
            MAILBOX("ring",  RING_STATUS),
            MAILBOX("middle_runner",  IC_MIDDLE_RUNNER),
            MAILBOX("middle_run",  IC_MIDDLE_RUN),
        SUBELEM_END("nocoltitles", NULL),


        SUBELEM_START("req", "requests", 2, 1)
            SUBELEM_START("vepp2000", "vepp2000", 12, 1)
                MAILBOX("request",  V2000_REQ),
                MAILBOX("fullcharge", V2000_FULLCHARGE ),
                MAILBOX("partcharge", V2000_PARTCHARGE ),
                MAILBOX("sentcharge", V2000_SENTCHARGE ),
                MAILBOX("recdcharge", V2000_RECDCHARGE ),
                MAILBOX("electron", V2000_ELECTRON ),
                MAILBOX("positron", V2000_POSITRON ),
                MAILBOX("ready", V2000_READY ),
                MAILBOX("lock", V2000_LOCK ),
                MAILBOX("acttime", V2000_ACTTIME ),
                MAILBOX("waittime", V2000_WAITTIME ),
                MAILBOX("act", V2000_ACT ),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("vepp3", "vepp3", 12, 1)
                MAILBOX("request",  V3_REQ),
                MAILBOX("fullcharge", V3_FULLCHARGE ),
                MAILBOX("partcharge", V3_PARTCHARGE ),
                MAILBOX("sentcharge", V3_SENTCHARGE ),
                MAILBOX("recdcharge", V3_RECDCHARGE ),
                MAILBOX("electron", V3_ELECTRON ),
                MAILBOX("positron", V3_POSITRON ),
                MAILBOX("ready", V3_READY ),
                MAILBOX("lock", V3_LOCK ),
                MAILBOX("acttime", V3_ACTTIME ),
                MAILBOX("waittime", V3_WAITTIME ),
                MAILBOX("act", V3_ACT ),
            SUBELEM_END("nocoltitles", NULL),
        SUBELEM_END("nocoltitles", NULL),

        SUBELEM_START("act", "Actions", 6, 1)
            MAILBOX("inject",  IC_INJECT),
            MAILBOX("extract",  IC_EXTRACT),
            MAILBOX("beam_stop",  IC_BEAM_STOP),
            MAILBOX("linac_powersave",  LINAC_POWERSAVE),
            MAILBOX("ring_powersave",  RING_POWERSAVE),

            SUBELEM_START("lin", "linac", 6, 1)
                MAILBOX("startmode",  LIN_STARTMODE),
                MAILBOX("startcycle", LIN_STARTCYCLE),
                MAILBOX("stopcycle",  LIN_STOPSYCLE),
                MAILBOX("startnum",  LIN_STARTNUM),
                MAILBOX("startcount",  LIN_STARTCOUNT),
                MAILBOX("eventcount",  LIN_EVENTCOUNT),
            SUBELEM_END("nocoltitles", NULL),
        SUBELEM_END("nocoltitles", NULL),


        SUBELEM_START("LLRF", "LLRF", 4, 1)
            MAILBOX("f_lin",  LINAC_F_RF),
            MAILBOX("f_ring",  RING_F_RF),
            MAILBOX("f_sub",  LINAC_F_SUB),
            MAILBOX("f_clockd16",  D16_F_CLOCK),
        SUBELEM_END("nocoltitles", NULL),

        TABBER_START("syn", "syn", 4)
            SUBELEM_START(":", "ctrl", 0, 1)
                MAILBOX("gen_mask",  LIN_RF_FSTART),
                MAILBOX("linrf_fstart",  LIN_RF_FSTART),
                MAILBOX("linbeam_fstart",  LIN_BEAM_FSTART),
                MAILBOX("linbeam_startmode",  LINAC_RF_FSTART),
            SUBELEM_END("nocoltitles", NULL),


            SUBELEM_START("linrf_dly", "linac RF", 0, 1)

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("linbeam_dly", "linac Beam", 0, 1)

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("ring", "ring", 0, 1)
            SUBELEM_END("nocoltitles", NULL),


        SUBELEM_END("left", NULL),

        TABBER_START("linac", "linac", 1)
            SUBELEM_START("mag", "mag", 0, 1)
            SUBELEM_END("nocoltitles", NULL),
        SUBELEM_END("left", NULL),

        TABBER_START("linmag", "linmag", 6)
            SUBELEM_START(":", "gen", 8, 1)
                MAILBOX("fail", LINMAG_FAIL),
                MAILBOX("switch", LINMAG_SWC),
                MAILBOX("middlerun", LINMAG_MIDDLE_RUN),
                MAILBOX("P", LINMAG_P),
                MAILBOX("Pmag", LINMAG_Pmag),
                MAILBOX("Pcab", LINMAG_Pcab),
                MAILBOX("Pair", LINMAG_Pair),
                MAILBOX("Pwater", LINMAG_Pwater),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START(":", "elinac_quad", 18, 6)

                SUBELEM_START("QL1", "QL1", 7, 1)
                   MAILBOX("Iset", LIN_QL1_I_SET),
                   MAILBOX("Imeas", LIN_QL1_I_MEAS),
                   MAILBOX("Gset", LIN_QL1_G_SET),
                   MAILBOX("Gmeas", LIN_QL1_G_MEAS),
                   MAILBOX("Pmag", LIN_QL1_P_MAG),
                   MAILBOX("Pcab", LIN_QL1_P_CAB),
                   MAILBOX("fail", LIN_QL1_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL2", "QL2", 7, 1)
                   MAILBOX("Iset", LIN_QL2_I_SET),
                   MAILBOX("Imeas", LIN_QL2_I_MEAS),
                   MAILBOX("Gset", LIN_QL2_G_SET),
                   MAILBOX("Gmeas", LIN_QL2_G_MEAS),
                   MAILBOX("Pmag", LIN_QL2_P_MAG),
                   MAILBOX("Pcab", LIN_QL2_P_CAB),
                   MAILBOX("fail", LIN_QL2_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL3", "QL3", 7, 1)
                   MAILBOX("Iset", LIN_QL3_I_SET),
                   MAILBOX("Imeas", LIN_QL3_I_MEAS),
                   MAILBOX("Gset", LIN_QL3_G_SET),
                   MAILBOX("Gmeas", LIN_QL3_G_MEAS),
                   MAILBOX("Pmag", LIN_QL3_P_MAG),
                   MAILBOX("Pcab", LIN_QL3_P_CAB),
                   MAILBOX("fail", LIN_QL3_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL4", "QL4", 7, 1)
                   MAILBOX("Iset", LIN_QL4_I_SET),
                   MAILBOX("Imeas", LIN_QL4_I_MEAS),
                   MAILBOX("Gset", LIN_QL4_G_SET),
                   MAILBOX("Gmeas", LIN_QL4_G_MEAS),
                   MAILBOX("Pmag", LIN_QL4_P_MAG),
                   MAILBOX("Pcab", LIN_QL4_P_CAB),
                   MAILBOX("fail", LIN_QL4_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL5", "QL5", 7, 1)
                   MAILBOX("Iset", LIN_QL5_I_SET),
                   MAILBOX("Imeas", LIN_QL5_I_MEAS),
                   MAILBOX("Gset", LIN_QL5_G_SET),
                   MAILBOX("Gmeas", LIN_QL5_G_MEAS),
                   MAILBOX("Pmag", LIN_QL5_P_MAG),
                   MAILBOX("Pcab", LIN_QL5_P_CAB),
                   MAILBOX("fail", LIN_QL5_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL6n7", "QL6n7", 7, 1)
                   MAILBOX("Iset", LIN_QL6_7_I_SET),
                   MAILBOX("Imeas", LIN_QL6_7_I_MEAS),
                   MAILBOX("Gset", LIN_QL6_7_G_SET),
                   MAILBOX("Gmeas", LIN_QL6_7_G_MEAS),
                   MAILBOX("Pmag", LIN_QL6_7_P_MAG),
                   MAILBOX("Pcab", LIN_QL6_7_P_CAB),
                   MAILBOX("fail", LIN_QL6_7_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL8n9", "QL8n9", 7, 1)
                   MAILBOX("Iset", LIN_QL8_9_I_SET),
                   MAILBOX("Imeas", LIN_QL8_9_I_MEAS),
                   MAILBOX("Gset", LIN_QL8_9_G_SET),
                   MAILBOX("Gmeas", LIN_QL8_9_G_MEAS),
                   MAILBOX("Pmag", LIN_QL8_9_P_MAG),
                   MAILBOX("Pcab", LIN_QL8_9_P_CAB),
                   MAILBOX("fail", LIN_QL8_9_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL10", "QL10", 7, 1)
                   MAILBOX("Iset", LIN_QL10_I_SET),
                   MAILBOX("Imeas", LIN_QL10_I_MEAS),
                   MAILBOX("Gset", LIN_QL10_G_SET),
                   MAILBOX("Gmeas", LIN_QL10_G_MEAS),
                   MAILBOX("Pmag", LIN_QL10_P_MAG),
                   MAILBOX("Pcab", LIN_QL10_P_CAB),
                   MAILBOX("fail", LIN_QL10_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL11", "QL11", 7, 1)
                   MAILBOX("Iset", LIN_QL11_I_SET),
                   MAILBOX("Imeas", LIN_QL11_I_MEAS),
                   MAILBOX("Gset", LIN_QL11_G_SET),
                   MAILBOX("Gmeas", LIN_QL11_G_MEAS),
                   MAILBOX("Pmag", LIN_QL11_P_MAG),
                   MAILBOX("Pcab", LIN_QL11_P_CAB),
                   MAILBOX("fail", LIN_QL11_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL12", "QL12", 7, 1)
                   MAILBOX("Iset", LIN_QL12_I_SET),
                   MAILBOX("Imeas", LIN_QL12_I_MEAS),
                   MAILBOX("Gset", LIN_QL12_G_SET),
                   MAILBOX("Gmeas", LIN_QL12_G_MEAS),
                   MAILBOX("Pmag", LIN_QL12_P_MAG),
                   MAILBOX("Pcab", LIN_QL12_P_CAB),
                   MAILBOX("fail", LIN_QL12_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL13", "QL13", 7, 1)
                   MAILBOX("Iset", LIN_QL13_I_SET),
                   MAILBOX("Imeas", LIN_QL13_I_MEAS),
                   MAILBOX("Gset", LIN_QL13_G_SET),
                   MAILBOX("Gmeas", LIN_QL13_G_MEAS),
                   MAILBOX("Pmag", LIN_QL13_P_MAG),
                   MAILBOX("Pcab", LIN_QL13_P_CAB),
                   MAILBOX("fail", LIN_QL13_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL14", "QL14", 7, 1)
                   MAILBOX("Iset", LIN_QL14_I_SET),
                   MAILBOX("Imeas", LIN_QL14_I_MEAS),
                   MAILBOX("Gset", LIN_QL14_G_SET),
                   MAILBOX("Gmeas", LIN_QL14_G_MEAS),
                   MAILBOX("Pmag", LIN_QL14_P_MAG),
                   MAILBOX("Pcab", LIN_QL14_P_CAB),
                   MAILBOX("fail", LIN_QL14_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLB1", "QLB1", 7, 1)
                   MAILBOX("Iset", LIN_QLB1_I_SET),
                   MAILBOX("Imeas", LIN_QLB1_I_MEAS),
                   MAILBOX("Gset", LIN_QLB1_G_SET),
                   MAILBOX("Gmeas", LIN_QLB1_G_MEAS),
                   MAILBOX("Pmag", LIN_QLB1_P_MAG),
                   MAILBOX("Pcab", LIN_QLB1_P_CAB),
                   MAILBOX("fail", LIN_QLB1_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLB2n5", "QLB2n5", 7, 1)
                   MAILBOX("Iset", LIN_QLB2_5_I_SET),
                   MAILBOX("Imeas", LIN_QLB2_5_I_MEAS),
                   MAILBOX("Gset", LIN_QLB2_5_G_SET),
                   MAILBOX("Gmeas", LIN_QLB2_5_G_MEAS),
                   MAILBOX("Pmag", LIN_QLB2_5_P_MAG),
                   MAILBOX("Pcab", LIN_QLB2_5_P_CAB),
                   MAILBOX("fail", LIN_QLB2_5_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLB3n4", "QLB3n4", 7, 1)
                   MAILBOX("Iset", LIN_QLB3_4_I_SET),
                   MAILBOX("Imeas", LIN_QLB3_4_I_MEAS),
                   MAILBOX("Gset", LIN_QLB3_4_G_SET),
                   MAILBOX("Gmeas", LIN_QLB3_4_G_MEAS),
                   MAILBOX("Pmag", LIN_QLB3_4_P_MAG),
                   MAILBOX("Pcab", LIN_QLB3_4_P_CAB),
                   MAILBOX("fail", LIN_QLB3_4_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLTR1", "QLTR1", 7, 1)
                   MAILBOX("Iset", LIN_QLTR1_I_SET),
                   MAILBOX("Imeas", LIN_QLTR1_I_MEAS),
                   MAILBOX("Gset", LIN_QLTR1_G_SET),
                   MAILBOX("Gmeas", LIN_QLTR1_G_MEAS),
                   MAILBOX("Pmag", LIN_QLTR1_P_MAG),
                   MAILBOX("Pcab", LIN_QLTR1_P_CAB),
                   MAILBOX("fail", LIN_QLTR1_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLTR2", "QLTR2", 7, 1)
                   MAILBOX("Iset", LIN_QLTR2_I_SET),
                   MAILBOX("Imeas", LIN_QLTR2_I_MEAS),
                   MAILBOX("Gset", LIN_QLTR2_G_SET),
                   MAILBOX("Gmeas", LIN_QLTR2_G_MEAS),
                   MAILBOX("Pmag", LIN_QLTR2_P_MAG),
                   MAILBOX("Pcab", LIN_QLTR2_P_CAB),
                   MAILBOX("fail", LIN_QLTR2_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLTR3", "QLTR3", 7, 1)
                   MAILBOX("Iset", LIN_QLTR3_I_SET),
                   MAILBOX("Imeas", LIN_QLTR3_I_MEAS),
                   MAILBOX("Gset", LIN_QLTR3_G_SET),
                   MAILBOX("Gmeas", LIN_QLTR3_G_MEAS),
                   MAILBOX("Pmag", LIN_QLTR3_P_MAG),
                   MAILBOX("Pcab", LIN_QLTR3_P_CAB),
                   MAILBOX("fail", LIN_QLTR3_FAIL),
                SUBELEM_END("nocoltitles", NULL),

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START(":", "elinac_corr", 0, 1)

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START(":", "plinac_quad", 18, 6)

                SUBELEM_START("QL15", "QL15", 7, 1)
                   MAILBOX("Iset", LIN_QL15_I_SET),
                   MAILBOX("Imeas", LIN_QL15_I_MEAS),
                   MAILBOX("Gset", LIN_QL15_G_SET),
                   MAILBOX("Gmeas", LIN_QL15_G_MEAS),
                   MAILBOX("Pmag", LIN_QL15_P_MAG),
                   MAILBOX("Pcab", LIN_QL15_P_CAB),
                   MAILBOX("fail", LIN_QL15_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QLN", "QLN", 7, 1)
                   MAILBOX("Iset", LIN_QLN_I_SET),
                   MAILBOX("Imeas", LIN_QLN_I_MEAS),
                   MAILBOX("Gset", LIN_QLN_G_SET),
                   MAILBOX("Gmeas", LIN_QLN_G_MEAS),
                   MAILBOX("Pmag", LIN_QLN_P_MAG),
                   MAILBOX("Pcab", LIN_QLN_P_CAB),
                   MAILBOX("fail", LIN_QLN_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL16", "QL16", 8, 1)
                   MAILBOX("Iset", LIN_QL16_I_SET),
                   MAILBOX("Imeas", LIN_QL16_I_MEAS),
                   MAILBOX("Gset", LIN_QL16_G_SET),
                   MAILBOX("Gmeas", LIN_QL16_G_MEAS),
                   MAILBOX("Pmag", LIN_QL16_P_MAG),
                   MAILBOX("Pcab", LIN_QL16_P_CAB),
                   MAILBOX("fail", LIN_QL16_FAIL),
                   MAILBOX("swc", LIN_QL16_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL17", "QL17", 8, 1)
                   MAILBOX("Iset", LIN_QL17_I_SET),
                   MAILBOX("Imeas", LIN_QL17_I_MEAS),
                   MAILBOX("Gset", LIN_QL17_G_SET),
                   MAILBOX("Gmeas", LIN_QL17_G_MEAS),
                   MAILBOX("Pmag", LIN_QL17_P_MAG),
                   MAILBOX("Pcab", LIN_QL17_P_CAB),
                   MAILBOX("fail", LIN_QL17_FAIL),
                   MAILBOX("swc", LIN_QL17_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL18", "QL18", 8, 1)
                   MAILBOX("Iset", LIN_QL18_I_SET),
                   MAILBOX("Imeas", LIN_QL18_I_MEAS),
                   MAILBOX("Gset", LIN_QL18_G_SET),
                   MAILBOX("Gmeas", LIN_QL18_G_MEAS),
                   MAILBOX("Pmag", LIN_QL18_P_MAG),
                   MAILBOX("Pcab", LIN_QL18_P_CAB),
                   MAILBOX("fail", LIN_QL18_FAIL),
                   MAILBOX("swc", LIN_QL18_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL19", "QL19", 8, 1)
                   MAILBOX("Iset", LIN_QL19_I_SET),
                   MAILBOX("Imeas", LIN_QL19_I_MEAS),
                   MAILBOX("Gset", LIN_QL19_G_SET),
                   MAILBOX("Gmeas", LIN_QL19_G_MEAS),
                   MAILBOX("Pmag", LIN_QL19_P_MAG),
                   MAILBOX("Pcab", LIN_QL19_P_CAB),
                   MAILBOX("fail", LIN_QL19_FAIL),
                   MAILBOX("swc", LIN_QL19_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL20", "QL20", 8, 1)
                   MAILBOX("Iset", LIN_QL20_I_SET),
                   MAILBOX("Imeas", LIN_QL20_I_MEAS),
                   MAILBOX("Gset", LIN_QL20_G_SET),
                   MAILBOX("Gmeas", LIN_QL20_G_MEAS),
                   MAILBOX("Pmag", LIN_QL20_P_MAG),
                   MAILBOX("Pcab", LIN_QL20_P_CAB),
                   MAILBOX("fail", LIN_QL20_FAIL),
                   MAILBOX("swc", LIN_QL20_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL21", "QL21", 8, 1)
                   MAILBOX("Iset", LIN_QL21_I_SET),
                   MAILBOX("Imeas", LIN_QL21_I_MEAS),
                   MAILBOX("Gset", LIN_QL21_G_SET),
                   MAILBOX("Gmeas", LIN_QL21_G_MEAS),
                   MAILBOX("Pmag", LIN_QL21_P_MAG),
                   MAILBOX("Pcab", LIN_QL21_P_CAB),
                   MAILBOX("fail", LIN_QL21_FAIL),
                   MAILBOX("swc", LIN_QL21_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL22", "QL22", 8, 1)
                   MAILBOX("Iset", LIN_QL22_I_SET),
                   MAILBOX("Imeas", LIN_QL22_I_MEAS),
                   MAILBOX("Gset", LIN_QL22_G_SET),
                   MAILBOX("Gmeas", LIN_QL22_G_MEAS),
                   MAILBOX("Pmag", LIN_QL22_P_MAG),
                   MAILBOX("Pcab", LIN_QL22_P_CAB),
                   MAILBOX("fail", LIN_QL22_FAIL),
                   MAILBOX("swc", LIN_QL22_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL23", "QL23", 8, 1)
                   MAILBOX("Iset", LIN_QL23_I_SET),
                   MAILBOX("Imeas", LIN_QL23_I_MEAS),
                   MAILBOX("Gset", LIN_QL23_G_SET),
                   MAILBOX("Gmeas", LIN_QL23_G_MEAS),
                   MAILBOX("Pmag", LIN_QL23_P_MAG),
                   MAILBOX("Pcab", LIN_QL23_P_CAB),
                   MAILBOX("fail", LIN_QL23_FAIL),
                   MAILBOX("swc", LIN_QL23_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL24", "QL24", 8, 1)
                   MAILBOX("Iset", LIN_QL24_I_SET),
                   MAILBOX("Imeas", LIN_QL24_I_MEAS),
                   MAILBOX("Gset", LIN_QL24_G_SET),
                   MAILBOX("Gmeas", LIN_QL24_G_MEAS),
                   MAILBOX("Pmag", LIN_QL24_P_MAG),
                   MAILBOX("Pcab", LIN_QL24_P_CAB),
                   MAILBOX("fail", LIN_QL24_FAIL),
                   MAILBOX("swc", LIN_QL24_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL25", "QL25", 8, 1)
                   MAILBOX("Iset", LIN_QL25_I_SET),
                   MAILBOX("Imeas", LIN_QL25_I_MEAS),
                   MAILBOX("Gset", LIN_QL25_G_SET),
                   MAILBOX("Gmeas", LIN_QL25_G_MEAS),
                   MAILBOX("Pmag", LIN_QL25_P_MAG),
                   MAILBOX("Pcab", LIN_QL25_P_CAB),
                   MAILBOX("fail", LIN_QL25_FAIL),
                   MAILBOX("swc", LIN_QL25_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL26", "QL26", 8, 1)
                   MAILBOX("Iset", LIN_QL26_I_SET),
                   MAILBOX("Imeas", LIN_QL26_I_MEAS),
                   MAILBOX("Gset", LIN_QL26_G_SET),
                   MAILBOX("Gmeas", LIN_QL26_G_MEAS),
                   MAILBOX("Pmag", LIN_QL26_P_MAG),
                   MAILBOX("Pcab", LIN_QL26_P_CAB),
                   MAILBOX("fail", LIN_QL26_FAIL),
                   MAILBOX("swc", LIN_QL26_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL27", "QL27", 8, 1)
                   MAILBOX("Iset", LIN_QL27_I_SET),
                   MAILBOX("Imeas", LIN_QL27_I_MEAS),
                   MAILBOX("Gset", LIN_QL27_G_SET),
                   MAILBOX("Gmeas", LIN_QL27_G_MEAS),
                   MAILBOX("Pmag", LIN_QL27_P_MAG),
                   MAILBOX("Pcab", LIN_QL27_P_CAB),
                   MAILBOX("fail", LIN_QL27_FAIL),
                   MAILBOX("swc", LIN_QL27_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL28", "QL28", 8, 1)
                   MAILBOX("Iset", LIN_QL28_I_SET),
                   MAILBOX("Imeas", LIN_QL28_I_MEAS),
                   MAILBOX("Gset", LIN_QL28_G_SET),
                   MAILBOX("Gmeas", LIN_QL28_G_MEAS),
                   MAILBOX("Pmag", LIN_QL28_P_MAG),
                   MAILBOX("Pcab", LIN_QL28_P_CAB),
                   MAILBOX("fail", LIN_QL28_FAIL),
                   MAILBOX("swc", LIN_QL28_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL29", "QL29", 8, 1)
                   MAILBOX("Iset", LIN_QL29_I_SET),
                   MAILBOX("Imeas", LIN_QL29_I_MEAS),
                   MAILBOX("Gset", LIN_QL29_G_SET),
                   MAILBOX("Gmeas", LIN_QL29_G_MEAS),
                   MAILBOX("Pmag", LIN_QL29_P_MAG),
                   MAILBOX("Pcab", LIN_QL29_P_CAB),
                   MAILBOX("fail", LIN_QL29_FAIL),
                   MAILBOX("swc", LIN_QL29_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL30", "QL30", 8, 1)
                   MAILBOX("Iset", LIN_QL30_I_SET),
                   MAILBOX("Imeas", LIN_QL30_I_MEAS),
                   MAILBOX("Gset", LIN_QL30_G_SET),
                   MAILBOX("Gmeas", LIN_QL30_G_MEAS),
                   MAILBOX("Pmag", LIN_QL30_P_MAG),
                   MAILBOX("Pcab", LIN_QL30_P_CAB),
                   MAILBOX("fail", LIN_QL30_FAIL),
                   MAILBOX("swc", LIN_QL30_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("QL31", "QL31", 8, 1)
                   MAILBOX("Iset", LIN_QL31_I_SET),
                   MAILBOX("Imeas", LIN_QL31_I_MEAS),
                   MAILBOX("Gset", LIN_QL31_G_SET),
                   MAILBOX("Gmeas", LIN_QL31_G_MEAS),
                   MAILBOX("Pmag", LIN_QL31_P_MAG),
                   MAILBOX("Pcab", LIN_QL31_P_CAB),
                   MAILBOX("fail", LIN_QL31_FAIL),
                   MAILBOX("swc", LIN_QL31_SWC),
                SUBELEM_END("nocoltitles", NULL),

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START(":", "plinac_corr", 0, 1)

            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START(":", "linac_other", 10, 5)
                SUBELEM_START("BL1", "BL1", 5, 1)
                   MAILBOX("Iset", LIN_BL1_I_SET),
                   MAILBOX("Imeas", LIN_BL1_I_MEAS),
                   MAILBOX("Pmag", LIN_BL1_P_MAG),
                   MAILBOX("Pcab", LIN_BL1_P_CAB),
                   MAILBOX("fail", LIN_BL1_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("BL2", "BL2", 5, 1)
                   MAILBOX("Iset", LIN_BL2_I_SET),
                   MAILBOX("Imeas", LIN_BL2_I_MEAS),
                   MAILBOX("Pmag", LIN_BL2_P_MAG),
                   MAILBOX("Pcab", LIN_BL2_P_CAB),
                   MAILBOX("fail", LIN_BL2_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("rings", "rings", 5, 1)
                   MAILBOX("Iset", LIN_RINGS_I_SET),
                   MAILBOX("Imeas", LIN_RINGS_I_MEAS),
                   MAILBOX("Pmag", LIN_RINGS_P_MAG),
                   MAILBOX("Pcab", LIN_RINGS_P_CAB),
                   MAILBOX("fail", LIN_RINGS_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("sole", "sole", 8, 1)
                   MAILBOX("Iset", LIN_SOLE_I_SET),
                   MAILBOX("Imeas", LIN_SOLE_I_MEAS),
                   MAILBOX("Umeas", LIN_SOLE_U_MEAS),
                   MAILBOX("Pmag", LIN_SOLE_P_MAG),
                   MAILBOX("Pcab", LIN_SOLE_P_CAB),
                   MAILBOX("fail", LIN_SOLE_FAIL),
                   MAILBOX("reset", LIN_SOLE_RESET),
                   MAILBOX("swc", LIN_SOLE_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("spectr", "spectr", 7, 1)
                   MAILBOX("Iset", LIN_SPECTR_I_SET),
                   MAILBOX("Imeas", LIN_SPECTR_I_MEAS),
                   MAILBOX("Hset", LIN_SPECTR_H_SET),
                   MAILBOX("Hmeas", LIN_SPECTR_H_MEAS),
                   MAILBOX("Pmag", LIN_SPECTR_P_MAG),
                   MAILBOX("Pcab", LIN_SPECTR_P_CAB),
                   MAILBOX("fail", LIN_SPECTR_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("bend", "bend", 12, 1)
                   MAILBOX("Iset", LIN_BEND_I_SET),
                   MAILBOX("Imeas", LIN_BEND_I_MEAS),
                   MAILBOX("Umeas", LIN_BEND_U_MEAS),
                   MAILBOX("Hset", LIN_BEND_H_SET),
                   MAILBOX("Hmeas", LIN_BEND_H_MEAS),
                   MAILBOX("PCset", LIN_BEND_PC_SET),
                   MAILBOX("PCmeas", LIN_BEND_PC_MEAS),
                   MAILBOX("Pmag", LIN_BEND_P_MAG),
                   MAILBOX("Pcab", LIN_BEND_P_CAB),
                   MAILBOX("fail", LIN_BEND_FAIL),
                   MAILBOX("reset", LIN_BEND_RESET),
                   MAILBOX("swc", LIN_BEND_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("coil1", "coil1", 8, 1)
                   MAILBOX("Iset", LIN_COIL1_I_SET),
                   MAILBOX("Imeas", LIN_COIL1_I_MEAS),
                   MAILBOX("Umeas", LIN_COIL1_U_MEAS),
                   MAILBOX("Pmag", LIN_COIL1_P_MAG),
                   MAILBOX("Pcab", LIN_COIL1_P_CAB),
                   MAILBOX("fail", LIN_COIL1_FAIL),
                   MAILBOX("reset", LIN_COIL1_RESET),
                   MAILBOX("swc", LIN_COIL1_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("coil2", "coil2", 5, 1)
                   MAILBOX("Iset", LIN_COIL2_I_SET),
                   MAILBOX("Imeas", LIN_COIL2_I_MEAS),
                   MAILBOX("Pmag", LIN_COIL2_P_MAG),
                   MAILBOX("Pcab", LIN_COIL2_P_CAB),
                   MAILBOX("fail", LIN_COIL2_FAIL),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("solp", "solp", 8, 1)
                   MAILBOX("Iset", LIN_SOLP_I_SET),
                   MAILBOX("Imeas", LIN_SOLP_I_MEAS),
                   MAILBOX("Umeas", LIN_SOLP_U_MEAS),
                   MAILBOX("Pmag", LIN_SOLP_P_MAG),
                   MAILBOX("Pcab", LIN_SOLP_P_CAB),
                   MAILBOX("fail", LIN_SOLP_FAIL),
                   MAILBOX("reset", LIN_SOLP_RESET),
                   MAILBOX("swc", LIN_SOLP_SWC),
                SUBELEM_END("nocoltitles", NULL),

                SUBELEM_START("sep1", "sep1", 7, 1)
                   MAILBOX("Iset", LIN_SEP1_I_SET),
                   MAILBOX("Imeas", LIN_SEP1_I_MEAS),
                   MAILBOX("Hset", LIN_SEP1_H_SET),
                   MAILBOX("Hmeas", LIN_SEP1_H_MEAS),
                   MAILBOX("Pmag", LIN_SEP1_P_MAG),
                   MAILBOX("Pcab", LIN_SEP1_P_CAB),
                   MAILBOX("fail", LIN_SEP1_FAIL),
                SUBELEM_END("nocoltitles", NULL),


            SUBELEM_END("nocoltitles", NULL),


        SUBELEM_END("left", NULL),

        TABBER_START("ring", "ring", 3)
            SUBELEM_START("dcct", "DCCT", 16, 1)
                MAILBOX("u2i", DCCT_U2I ),
                MAILBOX("ADCzero",  DCCT_ADC_ZERO),
                MAILBOX("meastime", DCCT_MEASTIME),
                MAILBOX("current", DCCT_BCURRENT),
                MAILBOX("storage_rate_calc", DCCT_STORAGE_RATE_CALC),
                MAILBOX("storage_fitlength", DCCT_STORAGE_FITLENGTH),
                MAILBOX("storage_rate", DCCT_STORAGE_RATE),
                MAILBOX("life_calc", DCCT_LIFETIME_CALC),
                MAILBOX("life_fitlength", DCCT_LIFE_FITLENGTH),
                MAILBOX("lifetime", DCCT_LIFETIME),
                MAILBOX("change", DCCT_CHARGE),
                MAILBOX("change_rate", DCCT_CHARGE_RATE),
                MAILBOX("n", DCCT_N),
                MAILBOX("n_rate", DCCT_N_RATE),
                MAILBOX("middle_run", DCCT_MEADDLE_RUN),
                MAILBOX("middle_lock", DCCT_MEADDLE_LOCK),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("magnets", "magnets", 1, 1)
                MAILBOX("rm1_rm8_B_set", RINGMAG_RM1_RM8_B_SET),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("RF", "RF", 0, 1)
            SUBELEM_END("nocoltitles", NULL),
        SUBELEM_END("left", NULL),

        TABBER_START("injext", "inj/ext", 4)
            SUBELEM_START("ctrl", "control", 2, 1)
                MAILBOX("middle_run", INJEXT_MIDDLE_RUN ),
                MAILBOX("Middle_lock", INJEXT_MIDDLE_LOCK ),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("ekicker", "ekickers", 22, 1)
                MAILBOX("ekick_mask", EKICK_START_MASK),
                MAILBOX("ekick_mask_rbv", EKICK_START_MASK_RBV),
                MAILBOX("ekick_start_mode", EKICK_START_MODE),
                MAILBOX("ekick_start_mode_rbv", EKICK_START_MODE_RBV),

                MAILBOX("gen_c1_dly", EKICK_GEN_C1_DLY),
                MAILBOX("gen_c2_dly", EKICK_GEN_C2_DLY),
                MAILBOX("gen_c3_dly", EKICK_GEN_C3_DLY),
                MAILBOX("gen_c4_dly", EKICK_GEN_C4_DLY),
                MAILBOX("form1p_dly", EKICK_FORM1P_DLY),
                MAILBOX("form1n_dly", EKICK_FORM1N_DLY),
                MAILBOX("form2p_dly", EKICK_FORM2P_DLY),
                MAILBOX("form2n_dly", EKICK_FORM2N_DLY),

                MAILBOX("gen_c1_mask", EKICK_GEN_C1_MASK),
                MAILBOX("gen_c2_mask", EKICK_GEN_C2_MASK),
                MAILBOX("gen_c3_mask", EKICK_GEN_C3_MASK),
                MAILBOX("gen_c4_mask", EKICK_GEN_C4_MASK),
                MAILBOX("form1p_mask", EKICK_FORM1P_MASK),
                MAILBOX("form1n_mask", EKICK_FORM1N_MASK),
                MAILBOX("form2p_mask", EKICK_FORM2P_MASK),
                MAILBOX("form2n_mask", EKICK_FORM2N_MASK),

                MAILBOX("u_akk1", EKICK_U_AKK1),
                MAILBOX("u_akk2", EKICK_U_AKK2),
            SUBELEM_END("nocoltitles", NULL),

            SUBELEM_START("ekicker_inj", "ekickers INJ", 18, 1)
                MAILBOX("gen_c1_dly_inj", EKICK_GEN_C1_DLY_INJ),
                MAILBOX("gen_c2_dly_inj", EKICK_GEN_C2_DLY_INJ),
                MAILBOX("gen_c3_dly_inj", EKICK_GEN_C3_DLY_INJ),
                MAILBOX("gen_c4_dly_inj", EKICK_GEN_C4_DLY_INJ),
                MAILBOX("form1p_dly_inj", EKICK_FORM1P_DLY_INJ),
                MAILBOX("form1n_dly_inj", EKICK_FORM1N_DLY_INJ),
                MAILBOX("form2p_dly_inj", EKICK_FORM2P_DLY_INJ),
                MAILBOX("form2n_dly_inj", EKICK_FORM2N_DLY_INJ),

                MAILBOX("gen_c1_mask_inj", EKICK_GEN_C1_MASK_INJ),
                MAILBOX("gen_c2_mask_inj", EKICK_GEN_C2_MASK_INJ),
                MAILBOX("gen_c3_mask_inj", EKICK_GEN_C3_MASK_INJ),
                MAILBOX("gen_c4_mask_inj", EKICK_GEN_C4_MASK_INJ),
                MAILBOX("form1p_mask_inj", EKICK_FORM1P_MASK_INJ),
                MAILBOX("form1n_mask_inj", EKICK_FORM1N_MASK_INJ),
                MAILBOX("form2p_mask_inj", EKICK_FORM2P_MASK_INJ),
                MAILBOX("form2n_mask_inj", EKICK_FORM2N_MASK_INJ),

                MAILBOX("u_akk1_inj", EKICK_U_AKK1_INJ),
                MAILBOX("u_akk2_inj", EKICK_U_AKK2_INJ),
            SUBELEM_END("nocoltitles", NULL),


            SUBELEM_START("ekicker_ext", "ekickers EXT", 18, 1)
                MAILBOX("gen_c1_dly_ext", EKICK_GEN_C1_DLY_EXT),
                MAILBOX("gen_c2_dly_ext", EKICK_GEN_C2_DLY_EXT),
                MAILBOX("gen_c3_dly_ext", EKICK_GEN_C3_DLY_EXT),
                MAILBOX("gen_c4_dly_ext", EKICK_GEN_C4_DLY_EXT),
                MAILBOX("form1p_dly_ext", EKICK_FORM1P_DLY_EXT),
                MAILBOX("form1n_dly_ext", EKICK_FORM1N_DLY_EXT),
                MAILBOX("form2p_dly_ext", EKICK_FORM2P_DLY_EXT),
                MAILBOX("form2n_dly_ext", EKICK_FORM2N_DLY_EXT),

                MAILBOX("gen_c1_mask_ext", EKICK_GEN_C1_MASK_EXT),
                MAILBOX("gen_c2_mask_ext", EKICK_GEN_C2_MASK_EXT),
                MAILBOX("gen_c3_mask_ext", EKICK_GEN_C3_MASK_EXT),
                MAILBOX("gen_c4_mask_ext", EKICK_GEN_C4_MASK_EXT),
                MAILBOX("form1p_mask_ext", EKICK_FORM1P_MASK_EXT),
                MAILBOX("form1n_mask_ext", EKICK_FORM1N_MASK_EXT),
                MAILBOX("form2p_mask_ext", EKICK_FORM2P_MASK_EXT),
                MAILBOX("form2n_mask_ext", EKICK_FORM2N_MASK_EXT),

                MAILBOX("u_akk1_ext", EKICK_U_AKK1_EXT),
                MAILBOX("u_akk2_ext", EKICK_U_AKK2_EXT),
            SUBELEM_END("nocoltitles", NULL),


        SUBELEM_END("left", NULL),

    GLOBELEM_END("", 0),


    {NULL}
};

static physprops_t ic_physinfo[] =
{
    {DCCT_U2I, 1000000.0, 0},
    {DCCT_ADC_ZERO, 1000000.0, 0},
    {DCCT_MEASTIME, 1000000.0, 0},
    {DCCT_BCURRENT, 1000000.0, 0},
    {DCCT_STORAGE_RATE, 1000000.0, 0},
    {DCCT_LIFETIME, 1000000.0, 0},
    {DCCT_CHARGE, 1000000.0, 0},
    {DCCT_CHARGE_RATE, 1000000.0, 0},
    {DCCT_N, 1000000.0, 0},
    {DCCT_N_RATE, 1000000.0, 0},
    {DCCT_I2CHARGE, 1000000.0, 0},
    {DCCT_I2N, 1000000.0, 0},

    // magnetic system
    {LINMAG_P, 1000.0, 0},
    {LINMAG_Pmag, 1000.0, 0},
    {LINMAG_Pcab, 1000.0, 0},
    {LINMAG_Pair, 1000.0, 0},
    {LINMAG_Pwater, 1000.0, 0},


    {LIN_QL1_I_SET, 1000000.0, 0},
    {LIN_QL1_I_MEAS, 1000000.0, 0},
    {LIN_QL1_G_SET, 1000000.0, 0},
    {LIN_QL1_G_MEAS, 1000000.0, 0},

    {LIN_QL2_I_SET, 1000000.0, 0},
    {LIN_QL2_I_MEAS, 1000000.0, 0},
    {LIN_QL2_G_SET, 1000000.0, 0},
    {LIN_QL2_G_MEAS, 1000000.0, 0},

    {LIN_QL3_I_SET, 1000000.0, 0},
    {LIN_QL3_I_MEAS, 1000000.0, 0},
    {LIN_QL3_G_SET, 1000000.0, 0},
    {LIN_QL3_G_MEAS, 1000000.0, 0},

    {LIN_QL4_I_SET, 1000000.0, 0},
    {LIN_QL4_I_MEAS, 1000000.0, 0},
    {LIN_QL4_G_SET, 1000000.0, 0},
    {LIN_QL4_G_MEAS, 1000000.0, 0},

    {LIN_QL5_I_SET, 1000000.0, 0},
    {LIN_QL5_I_MEAS, 1000000.0, 0},
    {LIN_QL5_G_SET, 1000000.0, 0},
    {LIN_QL5_G_MEAS, 1000000.0, 0},

    {LIN_QL6_7_I_SET, 1000000.0, 0},
    {LIN_QL6_7_I_MEAS, 1000000.0, 0},
    {LIN_QL6_7_G_SET, 1000000.0, 0},
    {LIN_QL6_7_G_MEAS, 1000000.0, 0},

    {LIN_QL8_9_I_SET, 1000000.0, 0},
    {LIN_QL8_9_I_MEAS, 1000000.0, 0},
    {LIN_QL8_9_G_SET, 1000000.0, 0},
    {LIN_QL8_9_G_MEAS, 1000000.0, 0},

    {LIN_QL10_I_SET, 1000000.0, 0},
    {LIN_QL10_I_MEAS, 1000000.0, 0},
    {LIN_QL10_G_SET, 1000000.0, 0},
    {LIN_QL10_G_MEAS, 1000000.0, 0},

    {LIN_QL11_I_SET, 1000000.0, 0},
    {LIN_QL11_I_MEAS, 1000000.0, 0},
    {LIN_QL11_G_SET, 1000000.0, 0},
    {LIN_QL11_G_MEAS, 1000000.0, 0},

    {LIN_QL12_I_SET, 1000000.0, 0},
    {LIN_QL12_I_MEAS, 1000000.0, 0},
    {LIN_QL12_G_SET, 1000000.0, 0},
    {LIN_QL12_G_MEAS, 1000000.0, 0},

    {LIN_QL13_I_SET, 1000000.0, 0},
    {LIN_QL13_I_MEAS, 1000000.0, 0},
    {LIN_QL13_G_SET, 1000000.0, 0},
    {LIN_QL13_G_MEAS, 1000000.0, 0},

    {LIN_QL14_I_SET, 1000000.0, 0},
    {LIN_QL14_I_MEAS, 1000000.0, 0},
    {LIN_QL14_G_SET, 1000000.0, 0},
    {LIN_QL14_G_MEAS, 1000000.0, 0},

    {LIN_QLB1_I_SET, 1000000.0, 0},
    {LIN_QLB1_I_MEAS, 1000000.0, 0},
    {LIN_QLB1_G_SET, 1000000.0, 0},
    {LIN_QLB1_G_MEAS, 1000000.0, 0},

    {LIN_QLB2_5_I_SET, 1000000.0, 0},
    {LIN_QLB2_5_I_MEAS, 1000000.0, 0},
    {LIN_QLB2_5_G_SET, 1000000.0, 0},
    {LIN_QLB2_5_G_MEAS, 1000000.0, 0},

    {LIN_QLB3_4_I_SET, 1000000.0, 0},
    {LIN_QLB3_4_I_MEAS, 1000000.0, 0},
    {LIN_QLB3_4_G_SET, 1000000.0, 0},
    {LIN_QLB3_4_G_MEAS, 1000000.0, 0},

    {LIN_QLTR1_I_SET, 1000000.0, 0},
    {LIN_QLTR1_I_MEAS, 1000000.0, 0},
    {LIN_QLTR1_G_SET, 1000000.0, 0},
    {LIN_QLTR1_G_MEAS, 1000000.0, 0},

    {LIN_QLTR2_I_SET, 1000000.0, 0},
    {LIN_QLTR2_I_MEAS, 1000000.0, 0},
    {LIN_QLTR2_G_SET, 1000000.0, 0},
    {LIN_QLTR2_G_MEAS, 1000000.0, 0},

    {LIN_QLTR3_I_SET, 1000000.0, 0},
    {LIN_QLTR3_I_MEAS, 1000000.0, 0},
    {LIN_QLTR3_G_SET, 1000000.0, 0},
    {LIN_QLTR3_G_MEAS, 1000000.0, 0},

    {LIN_QLN_I_SET, 100000.0, 0},
    {LIN_QLN_I_MEAS, 100000.0, 0},
    {LIN_QLN_G_SET, 100000.0, 0},
    {LIN_QLN_G_MEAS, 100000.0, 0},

    {LIN_QL15_I_SET, 1000000.0, 0},
    {LIN_QL15_I_MEAS, 1000000.0, 0},
    {LIN_QL15_G_SET, 1000000.0, 0},
    {LIN_QL15_G_MEAS, 1000000.0, 0},

    {LIN_QL16_I_SET, 1000000.0, 0},
    {LIN_QL16_I_MEAS, 1000000.0, 0},
    {LIN_QL16_G_SET, 1000000.0, 0},
    {LIN_QL16_G_MEAS, 1000000.0, 0},

    {LIN_QL17_I_SET, 1000000.0, 0},
    {LIN_QL17_I_MEAS, 1000000.0, 0},
    {LIN_QL17_G_SET, 1000000.0, 0},
    {LIN_QL17_G_MEAS, 1000000.0, 0},

    {LIN_QL18_I_SET, 1000000.0, 0},
    {LIN_QL18_I_MEAS, 1000000.0, 0},
    {LIN_QL18_G_SET, 1000000.0, 0},
    {LIN_QL18_G_MEAS, 1000000.0, 0},

    {LIN_QL19_I_SET, 1000000.0, 0},
    {LIN_QL19_I_MEAS, 1000000.0, 0},
    {LIN_QL19_G_SET, 1000000.0, 0},
    {LIN_QL19_G_MEAS, 1000000.0, 0},

    {LIN_QL20_I_SET, 1000000.0, 0},
    {LIN_QL20_I_MEAS, 1000000.0, 0},
    {LIN_QL20_G_SET, 1000000.0, 0},
    {LIN_QL20_G_MEAS, 1000000.0, 0},

    {LIN_QL21_I_SET, 1000000.0, 0},
    {LIN_QL21_I_MEAS, 1000000.0, 0},
    {LIN_QL21_G_SET, 1000000.0, 0},
    {LIN_QL21_G_MEAS, 1000000.0, 0},

    {LIN_QL22_I_SET, 1000000.0, 0},
    {LIN_QL22_I_MEAS, 1000000.0, 0},
    {LIN_QL22_G_SET, 1000000.0, 0},
    {LIN_QL22_G_MEAS, 1000000.0, 0},

    {LIN_QL23_I_SET, 1000000.0, 0},
    {LIN_QL23_I_MEAS, 1000000.0, 0},
    {LIN_QL23_G_SET, 1000000.0, 0},
    {LIN_QL23_G_MEAS, 1000000.0, 0},

    {LIN_QL24_I_SET, 1000000.0, 0},
    {LIN_QL24_I_MEAS, 1000000.0, 0},
    {LIN_QL24_G_SET, 1000000.0, 0},
    {LIN_QL24_G_MEAS, 1000000.0, 0},

    {LIN_QL25_I_SET, 1000000.0, 0},
    {LIN_QL25_I_MEAS, 1000000.0, 0},
    {LIN_QL25_G_SET, 1000000.0, 0},
    {LIN_QL25_G_MEAS, 1000000.0, 0},

    {LIN_QL26_I_SET, 1000000.0, 0},
    {LIN_QL26_I_MEAS, 1000000.0, 0},
    {LIN_QL26_G_SET, 1000000.0, 0},
    {LIN_QL26_G_MEAS, 1000000.0, 0},

    {LIN_QL27_I_SET, 1000000.0, 0},
    {LIN_QL27_I_MEAS, 1000000.0, 0},
    {LIN_QL27_G_SET, 1000000.0, 0},
    {LIN_QL27_G_MEAS, 1000000.0, 0},

    {LIN_QL28_I_SET, 1000000.0, 0},
    {LIN_QL28_I_MEAS, 1000000.0, 0},
    {LIN_QL28_G_SET, 1000000.0, 0},
    {LIN_QL28_G_MEAS, 1000000.0, 0},

    {LIN_QL29_I_SET, 1000000.0, 0},
    {LIN_QL29_I_MEAS, 1000000.0, 0},
    {LIN_QL29_G_SET, 1000000.0, 0},
    {LIN_QL29_G_MEAS, 1000000.0, 0},

    {LIN_QL30_I_SET, 1000000.0, 0},
    {LIN_QL30_I_MEAS, 1000000.0, 0},
    {LIN_QL30_G_SET, 1000000.0, 0},
    {LIN_QL30_G_MEAS, 1000000.0, 0},

    {LIN_QL31_I_SET, 1000000.0, 0},
    {LIN_QL31_I_MEAS, 1000000.0, 0},
    {LIN_QL31_G_SET, 1000000.0, 0},
    {LIN_QL31_G_MEAS, 1000000.0, 0},

    //other magnets channels
    {LIN_BL1_I_SET, 1000000.0, 0},
    {LIN_BL1_I_MEAS, 1000000.0, 0},

    {LIN_BL2_I_SET, 1000000.0, 0},
    {LIN_BL2_I_MEAS, 1000000.0, 0},

    {LIN_RINGS_I_SET, 1000000.0, 0},
    {LIN_RINGS_I_MEAS, 1000000.0, 0},

    {LIN_SOLE_I_SET, 1000000.0, 0},
    {LIN_SOLE_I_MEAS, 1000000.0, 0},
    {LIN_SOLE_U_MEAS, 1000000.0, 0},

    {LIN_SPECTR_I_SET, 1000000.0, 0},
    {LIN_SPECTR_I_MEAS, 1000000.0, 0},
    {LIN_SPECTR_H_SET, 1000000.0, 0},
    {LIN_SPECTR_H_MEAS, 1000000.0, 0},

    {LIN_BEND_I_SET, 1000000.0, 0},
    {LIN_BEND_I_MEAS, 1000000.0, 0},
    {LIN_BEND_U_MEAS, 1000000.0, 0},
    {LIN_BEND_H_SET, 1000000.0, 0},
    {LIN_BEND_H_MEAS, 1000000.0, 0},
    {LIN_BEND_PC_SET, 1000000.0, 0},
    {LIN_BEND_PC_MEAS, 1000000.0, 0},

    {LIN_COIL1_I_SET, 1000000.0, 0},
    {LIN_COIL1_I_MEAS, 1000000.0, 0},
    {LIN_COIL1_U_MEAS, 1000000.0, 0},

    {LIN_COIL2_I_SET, 1000000.0, 0},
    {LIN_COIL2_I_MEAS, 1000000.0, 0},

    {LIN_SOLP_I_SET, 1000000.0, 0},
    {LIN_SOLP_I_MEAS, 1000000.0, 0},
    {LIN_SOLP_U_MEAS, 1000000.0, 0},

    {LIN_SEP1_I_SET, 1000000.0, 0},
    {LIN_SEP1_I_MEAS, 1000000.0, 0},
    {LIN_SEP1_H_SET, 1000000.0, 0},
    {LIN_SEP1_H_MEAS, 1000000.0, 0},

    //magnetic system powers
    {LIN_QL1_P_MAG, 100000.0, 0},
    {LIN_QL1_P_CAB, 100000.0, 0},
    {LIN_QL2_P_MAG, 100000.0, 0},
    {LIN_QL2_P_CAB, 100000.0, 0},
    {LIN_QL3_P_MAG, 100000.0, 0},
    {LIN_QL3_P_CAB, 100000.0, 0},
    {LIN_QL4_P_MAG, 100000.0, 0},
    {LIN_QL4_P_CAB, 100000.0, 0},
    {LIN_QL5_P_MAG, 100000.0, 0},
    {LIN_QL5_P_CAB, 100000.0, 0},
    {LIN_QL6_7_P_MAG, 100000.0, 0},
    {LIN_QL6_7_P_CAB, 100000.0, 0},
    {LIN_QL8_9_P_MAG, 100000.0, 0},
    {LIN_QL8_9_P_CAB, 100000.0, 0},
    {LIN_QL10_P_MAG, 100000.0, 0},
    {LIN_QL10_P_CAB, 100000.0, 0},
    {LIN_QL11_P_MAG, 100000.0, 0},
    {LIN_QL11_P_CAB, 100000.0, 0},
    {LIN_QL12_P_MAG, 100000.0, 0},
    {LIN_QL12_P_CAB, 100000.0, 0},
    {LIN_QL13_P_MAG, 100000.0, 0},
    {LIN_QL13_P_CAB, 100000.0, 0},
    {LIN_QL14_P_MAG, 100000.0, 0},
    {LIN_QL14_P_CAB, 100000.0, 0},
    {LIN_QLB1_P_MAG, 100000.0, 0},
    {LIN_QLB1_P_CAB, 100000.0, 0},
    {LIN_QLB2_5_P_MAG, 100000.0, 0},
    {LIN_QLB2_5_P_CAB, 100000.0, 0},
    {LIN_QLB3_4_P_MAG, 100000.0, 0},
    {LIN_QLB3_4_P_CAB, 100000.0, 0},
    {LIN_QLTR1_P_MAG, 100000.0, 0},
    {LIN_QLTR1_P_CAB, 100000.0, 0},
    {LIN_QLTR2_P_MAG, 100000.0, 0},
    {LIN_QLTR2_P_CAB, 100000.0, 0},
    {LIN_QLTR3_P_MAG, 100000.0, 0},
    {LIN_QLTR3_P_CAB, 100000.0, 0},

    {LIN_QL15_P_MAG, 100000.0, 0},
    {LIN_QL15_P_CAB, 100000.0, 0},
    {LIN_QLN_P_MAG, 100000.0, 0},
    {LIN_QLN_P_CAB, 100000.0, 0},
    {LIN_QL16_P_MAG, 100000.0, 0},
    {LIN_QL16_P_CAB, 100000.0, 0},
    {LIN_QL17_P_MAG, 100000.0, 0},
    {LIN_QL17_P_CAB, 100000.0, 0},
    {LIN_QL18_P_MAG, 100000.0, 0},
    {LIN_QL18_P_CAB, 100000.0, 0},
    {LIN_QL19_P_MAG, 100000.0, 0},
    {LIN_QL19_P_CAB, 100000.0, 0},
    {LIN_QL21_P_MAG, 100000.0, 0},
    {LIN_QL21_P_CAB, 100000.0, 0},
    {LIN_QL22_P_MAG, 100000.0, 0},
    {LIN_QL22_P_CAB, 100000.0, 0},
    {LIN_QL23_P_MAG, 100000.0, 0},
    {LIN_QL23_P_CAB, 100000.0, 0},
    {LIN_QL24_P_MAG, 100000.0, 0},
    {LIN_QL24_P_CAB, 100000.0, 0},
    {LIN_QL25_P_MAG, 100000.0, 0},
    {LIN_QL25_P_CAB, 100000.0, 0},
    {LIN_QL26_P_MAG, 100000.0, 0},
    {LIN_QL26_P_CAB, 100000.0, 0},
    {LIN_QL27_P_MAG, 100000.0, 0},
    {LIN_QL27_P_CAB, 100000.0, 0},
    {LIN_QL28_P_MAG, 100000.0, 0},
    {LIN_QL28_P_CAB, 100000.0, 0},
    {LIN_QL29_P_MAG, 100000.0, 0},
    {LIN_QL29_P_CAB, 100000.0, 0},
    {LIN_QL30_P_MAG, 100000.0, 0},
    {LIN_QL30_P_CAB, 100000.0, 0},
    {LIN_QL31_P_MAG, 100000.0, 0},
    {LIN_QL31_P_CAB, 100000.0, 0},

    {LIN_BL1_P_MAG, 100000.0, 0},
    {LIN_BL1_P_CAB, 100000.0, 0},
    {LIN_BL2_P_MAG, 100000.0, 0},
    {LIN_BL2_P_CAB, 100000.0, 0},
    {LIN_RINGS_P_MAG, 100000.0, 0},
    {LIN_RINGS_P_CAB, 100000.0, 0},
    {LIN_SOLE_P_MAG, 100000.0, 0},
    {LIN_SOLE_P_CAB, 100000.0, 0},
    {LIN_SPECTR_P_MAG, 100000.0, 0},
    {LIN_SPECTR_P_CAB, 100000.0, 0},
    {LIN_BEND_P_MAG, 100000.0, 0},
    {LIN_BEND_P_CAB, 100000.0, 0},
    {LIN_COIL1_P_MAG, 100000.0, 0},
    {LIN_COIL1_P_CAB, 100000.0, 0},
    {LIN_COIL2_P_MAG, 100000.0, 0},
    {LIN_COIL2_P_CAB, 100000.0, 0},
    {LIN_SOLP_P_MAG, 100000.0, 0},
    {LIN_SOLP_P_CAB, 100000.0, 0},
    {LIN_SEP1_P_MAG, 100000.0, 0},
    {LIN_SEP1_P_CAB, 100000.0, 0},

    //electron injection channels
    {EKICK_GEN_C1_DLY, 1000000.0, 0},
    {EKICK_GEN_C2_DLY, 1000000.0, 0},
    {EKICK_GEN_C3_DLY, 1000000.0, 0},
    {EKICK_GEN_C4_DLY, 1000000.0, 0},
    {EKICK_FORM1P_DLY, 1000000.0, 0},
    {EKICK_FORM1N_DLY, 1000000.0, 0},
    {EKICK_FORM2P_DLY, 1000000.0, 0},
    {EKICK_FORM2N_DLY, 1000000.0, 0},
    {EKICK_U_AKK1, 1000000.0, 0},
    {EKICK_U_AKK2, 1000000.0, 0},


    {EKICK_GEN_C1_DLY_INJ, 1000000.0, 0},
    {EKICK_GEN_C2_DLY_INJ, 1000000.0, 0},
    {EKICK_GEN_C3_DLY_INJ, 1000000.0, 0},
    {EKICK_GEN_C4_DLY_INJ, 1000000.0, 0},
    {EKICK_FORM1P_DLY_INJ, 1000000.0, 0},
    {EKICK_FORM1N_DLY_INJ, 1000000.0, 0},
    {EKICK_FORM2P_DLY_INJ, 1000000.0, 0},
    {EKICK_FORM2N_DLY_INJ, 1000000.0, 0},
    {EKICK_U_AKK1_INJ, 1000000.0, 0},
    {EKICK_U_AKK2_INJ, 1000000.0, 0},

    {EKICK_GEN_C1_DLY_EXT, 1000000.0, 0},
    {EKICK_GEN_C2_DLY_EXT, 1000000.0, 0},
    {EKICK_GEN_C3_DLY_EXT, 1000000.0, 0},
    {EKICK_GEN_C4_DLY_EXT, 1000000.0, 0},
    {EKICK_FORM1P_DLY_EXT, 1000000.0, 0},
    {EKICK_FORM1N_DLY_EXT, 1000000.0, 0},
    {EKICK_FORM2P_DLY_EXT, 1000000.0, 0},
    {EKICK_FORM2N_DLY_EXT, 1000000.0, 0},
    {EKICK_U_AKK1_EXT, 1000000.0, 0},
    {EKICK_U_AKK2_EXT, 1000000.0, 0},

    {RINGMAG_RM1_RM8_B_SET, 1000000.0, 0},

};
