SUBDIRS=	drv_i

EXPORTSFILES=	tsycamlib.h gray2image.h
EXPORTSDIR=	include

######################################################################
PRJDIR=		..
include		$(PRJDIR)/PrjRules.mk
######################################################################
