APP_PIXMAPS=	cxmnaf cx-starter magnet
TOOLBAR_PIXMAPS=$(addprefix btn_, elog getbkgd help log once open pause print quit rstbkgd rstgood save setgood start)
MINI_PIXMAPS=	$(addprefix btn_mini_, save start once)
ALL_PIXMAPS=	$(addsuffix .xpm, $(APP_PIXMAPS) $(TOOLBAR_PIXMAPS) $(MINI_PIXMAPS))

GIVEN_FILES=	$(ALL_PIXMAPS)

EXPORTSFILES=	$(ALL_PIXMAPS)
EXPORTSDIR=	include/pixmaps

######################################################################
TOPDIR=	        ../..
include		$(TOPDIR)/TopRules.mk
######################################################################
