MONO_C_FILES=	slbpm_drv.so

######################################################################
PRJDIR=		../..
SECTION=	programs/drivers/DirRules.mk
include		$(PRJDIR)/PrjRules.mk
######################################################################

slbpm_drv.so:	$(LIBPZFRAME_DRV)
