SUBDIRS=	include lib x-build drivers chlclients
ifeq "$(NOX)" ""
  SUBDIRS+=	xmclients
  SUBDIRS+=	pzframes
endif

######################################################################
PRJDIR=		.
include		$(PRJDIR)/PrjRules.mk
######################################################################
