######################################################################
#                                                                    #
#  lib/Chl/Makefile                                                  #
#      Rules for making Cx High-Level library                        #
#                                                                    #
######################################################################

ARLIBS=		libChl.a
libChl.a_COMPONENTS=	Chl_privrec.o Chl_err.o \
			Chl_app.o Chl_gui.o \
			Chl_knobprops.o

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
