#ifndef __CANADC40_DRV_I_H
#define __CANADC40_DRV_I_H


#include "drv_i/cankoz_common_drv_i.h"


enum
{
    CANADC40_CHAN_READ_N_BASE   = 0,  CANADC40_CHAN_READ_N_COUNT = 40,
    CANADC40_CHAN_REGS_BASE     = 40,
    
    CANADC40_CHAN_REGS_WR8_BASE = CANADC40_CHAN_REGS_BASE + CANKOZ_REGS_WR8_BOFS,
    CANADC40_CHAN_REGS_RD8_BASE = CANADC40_CHAN_REGS_BASE + CANKOZ_REGS_RD8_BOFS,
    CANADC40_CHAN_REGS_WR1      = CANADC40_CHAN_REGS_BASE + CANKOZ_REGS_WR1_OFS,
    CANADC40_CHAN_REGS_RD1      = CANADC40_CHAN_REGS_BASE + CANKOZ_REGS_RD1_OFS,
    CANADC40_CHAN_REGS_LAST     = CANADC40_CHAN_REGS_BASE + CANKOZ_REGS_NUMCHANS -1,

    CANADC40_NUMCHANS           = CANADC40_CHAN_REGS_LAST + 1
};


#endif /* __CANADC40_DRV_I_H */
