#ifndef __CDAC20_DRV_I_H
#define __CDAC20_DRV_I_H


#include "drv_i/cankoz_common_drv_i.h"


enum
{
    CDAC20_CHAN_READ_N_BASE = 0, CDAC20_CHAN_READ_N_COUNT = 8,
    CDAC20_CHAN_WRITE       = 8,
    CDAC20_CHAN_DUMMY       = 9, // This is just for padding
    CDAC20_CHAN_REGS_BASE   = 10,

    CDAC20_CHAN_REGS_WR8_BASE = CDAC20_CHAN_REGS_BASE + CANKOZ_REGS_WR8_BOFS,
    CDAC20_CHAN_REGS_RD8_BASE = CDAC20_CHAN_REGS_BASE + CANKOZ_REGS_RD8_BOFS,
    CDAC20_CHAN_REGS_WR1      = CDAC20_CHAN_REGS_BASE + CANKOZ_REGS_WR1_OFS,
    CDAC20_CHAN_REGS_RD1      = CDAC20_CHAN_REGS_BASE + CANKOZ_REGS_RD1_OFS,
    CDAC20_CHAN_REGS_LAST     = CDAC20_CHAN_REGS_BASE + CANKOZ_REGS_NUMCHANS -1,

    CDAC20_NUMCHANS           = CDAC20_CHAN_REGS_LAST + 1
};

enum
{
    CDAC20_CHAN_READ_DAC  = CDAC20_CHAN_READ_N_BASE + CDAC20_CHAN_READ_N_COUNT - 3,
    CDAC20_CHAN_READ_0V   = CDAC20_CHAN_READ_N_BASE + CDAC20_CHAN_READ_N_COUNT - 2,
    CDAC20_CHAN_READ_P10V = CDAC20_CHAN_READ_N_BASE + CDAC20_CHAN_READ_N_COUNT - 1,
};


#endif /* __CDAC20_DRV_I_H */
