#ifndef __CGVI8_DRV_I_H
#define __CGVI8_DRV_I_H


#include "drv_i/cankoz_common_drv_i.h"


// w8,w8,w8,w1,w1,w1,w1,w8,r8,w1,r1
enum
{
    CGVI8_CHAN_16BIT_N_BASE  = 0,   CGVI8_CHAN_WORK_COUNT = 8,
    CGVI8_CHAN_QUANT_N_BASE  = 8,   // Note: 1quant=100ns
    CGVI8_CHAN_MASK1_N_BASE  = 16,
    CGVI8_CHAN_MASK8         = 24,
    CGVI8_CHAN_PROGSTART     = 25,
    CGVI8_CHAN_PRESCALER     = 26,
    CGVI8_CHAN_BASEBYTE      = 27,
    CGVI8_CHAN_REGS_BASE     = 28,
    
    CGVI8_CHAN_REGS_WR8_BASE = CGVI8_CHAN_REGS_BASE + CANKOZ_REGS_WR8_BOFS,
    CGVI8_CHAN_REGS_RD8_BASE = CGVI8_CHAN_REGS_BASE + CANKOZ_REGS_RD8_BOFS,
    CGVI8_CHAN_REGS_WR1      = CGVI8_CHAN_REGS_BASE + CANKOZ_REGS_WR1_OFS,
    CGVI8_CHAN_REGS_RD1      = CGVI8_CHAN_REGS_BASE + CANKOZ_REGS_RD1_OFS,
    CGVI8_CHAN_REGS_LAST     = CGVI8_CHAN_REGS_BASE + CANKOZ_REGS_NUMCHANS -1,

    CGVI8_NUMCHANS           = CGVI8_CHAN_REGS_LAST + 1
};


#endif /* __CGVI8_DRV_I_H */
