#ifndef __XCDAC20_DRV_I_H
#define __XCDAC20_DRV_I_H


#include "drv_i/kozdev_common_drv_i.h"


// w40,r20,w8,r8,w1,r1,r22,r100,w64,r36
enum
{
    XCDAC20_CONFIG_CHAN_base     = KOZDEV_CONFIG_CHAN_base,
      XCDAC20_CONFIG_CHAN_count  = KOZDEV_CONFIG_CHAN_count,

    /*  */
    XCDAC20_MODE_CHAN_base       = KOZDEV_MODE_CHAN_base,
      XCDAC20_MODE_CHAN_count    = KOZDEV_MODE_CHAN_count,

    XCDAC20_CHAN_DO_RESET        = KOZDEV_CHAN_DO_RESET,
    XCDAC20_CHAN_ADC_MODE        = KOZDEV_CHAN_ADC_MODE,
    XCDAC20_CHAN_ADC_BEG         = KOZDEV_CHAN_ADC_BEG,
    XCDAC20_CHAN_ADC_END         = KOZDEV_CHAN_ADC_END,
    XCDAC20_CHAN_ADC_TIMECODE    = KOZDEV_CHAN_ADC_TIMECODE,
    XCDAC20_CHAN_ADC_GAIN        = KOZDEV_CHAN_ADC_GAIN,
    XCDAC20_CHAN_RESERVED6       = KOZDEV_CHAN_RESERVED6,
    XCDAC20_CHAN_RESERVED7       = KOZDEV_CHAN_RESERVED7,
    XCDAC20_CHAN_RESERVED8       = KOZDEV_CHAN_RESERVED8,
    XCDAC20_CHAN_OUT_MODE        = KOZDEV_CHAN_OUT_MODE,

    XCDAC20_CHAN_DO_TAB_DROP     = KOZDEV_CHAN_DO_TAB_DROP,
    XCDAC20_CHAN_DO_TAB_ACTIVATE = KOZDEV_CHAN_DO_TAB_ACTIVATE,
    XCDAC20_CHAN_DO_TAB_START    = KOZDEV_CHAN_DO_TAB_START,
    XCDAC20_CHAN_DO_TAB_STOP     = KOZDEV_CHAN_DO_TAB_STOP,
    XCDAC20_CHAN_DO_TAB_PAUSE    = KOZDEV_CHAN_DO_TAB_PAUSE,
    XCDAC20_CHAN_DO_TAB_RESUME   = KOZDEV_CHAN_DO_TAB_RESUME,
      XCDAC20_CHAN_DO_TAB_base = KOZDEV_CHAN_DO_TAB_base,
      XCDAC20_CHAN_DO_TAB_cnt  = KOZDEV_CHAN_DO_TAB_cnt,
    XCDAC20_CHAN_RESERVED16      = KOZDEV_CHAN_RESERVED16,
    XCDAC20_CHAN_RESERVED17      = KOZDEV_CHAN_RESERVED17,
    XCDAC20_CHAN_RESERVED18      = KOZDEV_CHAN_RESERVED18,
    XCDAC20_CHAN_RESERVED19      = KOZDEV_CHAN_RESERVED19,

    /*  */
    XCDAC20_CHAN_STD_WR_base     = KOZDEV_CHAN_STD_WR_base,
      XCDAC20_CHAN_STD_WR_count  = KOZDEV_CHAN_STD_WR_count,
    XCDAC20_CHAN_DO_CALB_DAC     = KOZDEV_CHAN_DO_CALB_DAC,
    XCDAC20_CHAN_AUTOCALB_ONOFF  = KOZDEV_CHAN_AUTOCALB_ONOFF,
    XCDAC20_CHAN_AUTOCALB_SECS   = KOZDEV_CHAN_AUTOCALB_SECS,
    XCDAC20_CHAN_DIGCORR_MODE    = KOZDEV_CHAN_DIGCORR_MODE,

    /*  */
    XCDAC20_CHAN_STD_RD_base     = KOZDEV_CHAN_STD_RD_base,
      XCDAC20_CHAN_STD_RD_count  = KOZDEV_CHAN_STD_RD_count,
    XCDAC20_CHAN_HW_VER          = KOZDEV_CHAN_HW_VER,
    XCDAC20_CHAN_SW_VER          = KOZDEV_CHAN_SW_VER,
    XCDAC20_CHAN_DIGCORR_VALID   = KOZDEV_CHAN_DIGCORR_VALID,
    XCDAC20_CHAN_DIGCORR_FACTOR  = KOZDEV_CHAN_DIGCORR_FACTOR,

    /*** I/O registers **********************************************/
    XCDAC20_CHAN_REGS_base       = KOZDEV_CHAN_REGS_base,
    XCDAC20_CHAN_REGS_WR8_base   = KOZDEV_CHAN_REGS_WR8_base,
    XCDAC20_CHAN_REGS_RD8_base   = KOZDEV_CHAN_REGS_RD8_base,
    XCDAC20_CHAN_REGS_WR1        = KOZDEV_CHAN_REGS_WR1,
    XCDAC20_CHAN_REGS_RD1        = KOZDEV_CHAN_REGS_RD1,
    XCDAC20_CHAN_REGS_last       = KOZDEV_CHAN_REGS_last,

    XCDAC20_CHAN_REGS_RSVD_B     = KOZDEV_CHAN_REGS_RSVD_B,
    XCDAC20_CHAN_REGS_RSVD_E     = KOZDEV_CHAN_REGS_RSVD_E,

    /* Regular ADC/DAC channels *************************************/
    XCDAC20_CHAN_ADC_n_base      = KOZDEV_CHAN_ADC_n_base,
      XCDAC20_CHAN_ADC_n_count   = 8,
      XCDAC20_CHAN_ADC_n_maxcnt  = KOZDEV_CHAN_ADC_n_maxcnt,

    XCDAC20_CHAN_OUT_n_base      = KOZDEV_CHAN_OUT_n_base,
      XCDAC20_CHAN_OUT_n_count   = 1,
      XCDAC20_CHAN_OUT_n_maxcnt  = KOZDEV_CHAN_OUT_n_maxcnt,
    XCDAC20_CHAN_OUT_RATE_n_base = KOZDEV_CHAN_OUT_RATE_n_base,
    XCDAC20_CHAN_OUT_CUR_n_base  = KOZDEV_CHAN_OUT_CUR_n_base,
      XCDAC20_CHAN_OUT_RESERVED_count = KOZDEV_CHAN_OUT_RESERVED_count,

    XCDAC20_NUMCHANS = KOZDEV_NUMCHANS
};

enum
{
    XCDAC20_CHAN_ADC_DAC  = XCDAC20_CHAN_ADC_n_base + XCDAC20_CHAN_ADC_n_count - 3,
    XCDAC20_CHAN_ADC_0V   = XCDAC20_CHAN_ADC_n_base + XCDAC20_CHAN_ADC_n_count - 2,
    XCDAC20_CHAN_ADC_P10V = XCDAC20_CHAN_ADC_n_base + XCDAC20_CHAN_ADC_n_count - 1,
};

// 8*1+58i/1+58i,1*1+261i/1+261i
enum
{
    XCDAC20_BIGC_ITAB_n_base = 0, // Individual per-channel tables
    XCDAC20_BIGC_TAB_WHOLE   = 8, // Whole-channels table -- =XCDAC20_BIGC_ITABLE_n_base+XCDAC20_CHAN_OUT_n_count

    XCDAC20_NUM_BIGCS          = 9
};

enum
{
    XCDAC20_ADC_MODE_NORM   = 0,
    XCDAC20_ADC_MODE_OSCILL = 1,
    XCDAC20_ADC_MODE_PLOT   = 2,
    XCDAC20_ADC_MODE_TBACK  = 3,
};

enum
{
    XCDAC20_OUT_MODE_NORM   = 0,
    XCDAC20_OUT_MODE_TABLE  = 1,
};

enum
{
    XCDAC20_VAL_DISABLE_TABLE_CHAN = 20*1000*1000,  // 20V or higher -- disable channel

};


#endif /* __XCDAC20_DRV_I_H */
