#ifndef __YAMKSHD8_DRV_I_H
#define __YAMKSHD8_DRV_I_H


enum
{
    YAMKSHD8_NUMLINES = 8,
};


// r96,w104
enum
{
    YAMKSHD8_G_GOING        = 0,
    YAMKSHD8_G_COUNTER      = 1,
    YAMKSHD8_G_2            = 2,
    YAMKSHD8_G_3            = 3,
    YAMKSHD8_G_4            = 4,
    YAMKSHD8_G_5            = 5,
    YAMKSHD8_G_6            = 6,
    YAMKSHD8_G_7            = 7,
    YAMKSHD8_G_8            = 8,
    YAMKSHD8_G_9            = 9,
    YAMKSHD8_G_10           = 10,
    YAMKSHD8_G_11           = 11,
    YAMKSHD8_G_MIN_VELOCITY = 12,
    YAMKSHD8_G_MAX_VELOCITY = 13,
    YAMKSHD8_G_ACCELERATION = 14,
    YAMKSHD8_G_T_ACCEL      = 15,
    YAMKSHD8_G_NUM_STEPS    = 16,
    YAMKSHD8_G_GO           = 17,
    YAMKSHD8_G_STOP         = 18,
    YAMKSHD8_G_RST_COUNTER  = 19,
    YAMKSHD8_G_20           = 20,
    YAMKSHD8_G_21           = 21,
    YAMKSHD8_G_22           = 22,
    YAMKSHD8_G_23           = 23,
    YAMKSHD8_G_24           = 24,

    YAMKSHD8_CHAN_GOING_base        = YAMKSHD8_G_GOING        * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_COUNTER_base      = YAMKSHD8_G_COUNTER      * YAMKSHD8_NUMLINES,

    YAMKSHD8_CHAN_MIN_VELOCITY_base = YAMKSHD8_G_MIN_VELOCITY * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_MAX_VELOCITY_base = YAMKSHD8_G_MAX_VELOCITY * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_ACCELERATION_base = YAMKSHD8_G_ACCELERATION * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_T_ACCEL_base      = YAMKSHD8_G_T_ACCEL      * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_NUM_STEPS_base    = YAMKSHD8_G_NUM_STEPS    * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_GO_base           = YAMKSHD8_G_GO           * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_STOP_base         = YAMKSHD8_G_STOP         * YAMKSHD8_NUMLINES,
    YAMKSHD8_CHAN_RST_COUNTER_base  = YAMKSHD8_G_RST_COUNTER  * YAMKSHD8_NUMLINES,

    YAMKSHD8_NUMCHANS = 200,
};


#endif /* __YAMKSHD8_DRV_I_H */
