######################################################################
#                                                                    #
#  lib/datatree/Makefile                                             #
#      Rules for making Data Tree library                            #
#                                                                    #
######################################################################

ARLIBS=		libdatatree.a
libdatatree.a_COMPONENTS=	datatree.o

TOPDIR=         ../..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
