######################################################################
#                                                                    #
#  doc/Makefile                                                      #
#      Rules for making CX doc/ (documentation) subtree              #
#                                                                    #
######################################################################

SUBDIRS=	lib
TOPDIR=		..
include $(TOPDIR)/TopRules.mk

# #### END OF Makefile ###############################################
